//
//  Jokes.swift
//  WhatZodiacSignIsThis
//
//  Created by MyMac on 8/31/23.
//

import Foundation

// A jokes dictionary that will accept a String for the key and an array of Strings for the values
struct Jokes {
    
    static let shared = Jokes()
    
    let jokesArray: [String: [String]] = [
        "AriesButton": [
            "I don't wait for elevators; I take the stairs. Who has time to stand around?",
            "New restaurant? I'm there! I live for taste adventures.",
            "Sports? I don't just watch; I compete with the players from my couch!",
            "Personal trainer? Nah, I'm the life coach of my own journey!",
            "A rock band? Count me in! I've got enough energy to light up a stadium!",
            "If u ain't making 6 figures BEAT ITT!!!",
            "Dumb sh*t irritates me like people clapping when the plane lands",
            "One red flag & I'm Casper the ghost. You will not see me",
            "When u talk & people are playing with their phones so u cut the WiFi",
            "If I order a burger with no onions & u add them, don't be shocked when I fake an allergic reaction",
            "I get drunk and start buying drinks for total strangers",
            "I really need to stop buying stupid things when I get paid",
            "I've got 99 problems and 86 of them are completely made-up scenarios in my head",
            "Quit my job this morning..started only fans this afternoon",
            "Pretending to be listening but actually planning on when to interrupt u",
            "Don't tell me good morning, that's for me to decide",
            "I get hurt & immediately go into hustle mode",
            "5'5 and under?! Ew, no thanks leprechaun",
            "Patience shorter than ur gf ponytail",
            "It takes me .001 sec to pick out my clothes for the day..I truly dgaf",
            "Bring back saying 'take a hike.' It's so wildly dismissive without being vulgar",
            "If I request a Lyft and u can't be here in 5 mins don't bother showing up",
            "Once she falls in love, I fall out of character..and CUT!",
            "If I offer u food DO NOT accept it, I was being fake nice",
            "It grinds my gears when y'all talk with crust in the cracks of ya'll mouth",
            "I talk to people in their native accent, I just can't help it LMAO",
            "What if I told u explaining something with a clever metaphor doesn't make u right",
            "Sometimes I wake up, hear y'all breathe and get pissed off",
            "I may make impulsive decisions, but at least they're never boring",
            "Meet my friend dial..TONE..clickk!!",
            "I can't stand a know-it-all..bet u ain't know I slept with ur man haa!",
            "Once we break up… 'Hello, 911..I'd like to report a drug smuggler'",
            "Are those cloth interior seats? LMFAO",
            "I'm not stopping at two red-lights in a row, the first one counts for both",
            "Once temp reaches 70..hoochie daddy shorts in full effect",
            "Ur man this, ur man that. Ur man stays in my DM!!",
            "As a grown man, why are u wearing a bob? that infuriates me",
            "Just bought a house without inspection. A gang of roaches just asked for the 1st month's rent",
            "If I'm too much, then go find less",
            "EAT IT or BEAT IT!!",
            "Invested my entire savings in crypto..now I can't even afford super mario coins"
        ]
,
        "TaurusButton": [
            "Buffet? That's where I set up camp, sampling all the delights.",
            "Puzzle? I won't quit until every piece finds its place!",
            "Movie night? Classic films, cozy blankets, and my comfort zone intact.",
            "Gardening? I'm in. The patience for growth runs in my roots.",
            "Umbrella? Always ready. I'm the dependable one in every storm.",
            "I completely restart my PC after a Zoom call; I refuse to be caught lacking.",
            "Monday again, time to get to this job, be fake & act like I like people.",
            "If I finish washing dishes & forget one, I'm throwing it out.",
            "I even keep my family out of my business; they'll talk about u too.",
            "I'm already on my like 3rd life. Don't make it 4!!",
            "When your plan is canceled & you can stay home all night like you wanted to all along.",
            "No one will know where I live; meet me at the gas station LMAO.",
            "I'm not insecure, just not with all that friendly sh*t.",
            "Why would I drive 3 min away for pickup when I can order Uber Eats for $79.95.",
            "How do you know my full government name? Who sent u?!",
            "I gotta stay high; people are annoying.",
            "You don't need to stay in bed all day said the weirdo.",
            "Don't ring my doorbell if you didn’t set an appointment.",
            "Yes, I'll meet y'all there!... ME: knowing damn well I'm not going.",
            "HMMM GET SOMEBODY ELSE TO DO IT!!",
            "Knowing your worth will have your phone dry af.",
            "Looking at the menu even though they're going to get the same thing as usual.",
            "I have eaten 22 times and taken 13 naps and it's still today.",
            "My cup was placed on the table at a 90-degree angle and now it's at 40... who's been in my house?",
            "Don’t ask me why I'm single... I need money, not love fool.",
            "I'm not a hoarder; I'm just sentimental about my stuff.",
            "Sitting back & watching things happen they said would happen.",
            "Do NOT breathe heavy around me; I already don't like people as it is.",
            "Doing nothing is my biggest hobby.",
            "I'm a thinker so make sure all your sh*t adds up before I start calculating.",
            "I'm half extroverted, half introverted. I like to hang out and then spend days alone to recharge.",
            "I need a vacation to recover from my vacation.",
            "If you see me looking zoned out it's because I'm having a therapy session with myself in my head.",
            "U got IG? NO... FB? NO, What's your name? NO.",
            "One of the FREAKIEST AND NASTIEST people you'll ever meet IF I like u.",
            "WHO ALL GON BE THERE?",
            "Now why u invite me out knowing there would be people in the public?!",
            "Scared to get your heartbroken? break theirs first.",
            "I check ID's and baby pics now; these surgeries are getting out of hand.",
            "The ULTIMATE Homebody.",
            "If I run an errand, that is considered going out... argue with ur mama."
        ]
,
        "GeminiButton": [
            "Texting? I could have a full conversation before you finish your sentence!",
            "Music? I've got playlists for every mood and scenario.",
            "Indecisiveness? I've mastered the art of keeping options open.",
            "Two-faced? Nah, I'm just well-equipped for different situations.",
            "Socializing? I thrive in crowds and can charm anyone within seconds.",
            "I will cheat on u & beg to get back, be good for a week & cheat again",
            "When u pay her rent but she tell social media god made a way",
            "Worst texter alive but a vibe in real life",
            "My 12th time starting this diet, this time will be different",
            "Calling me ur EX is crazyyy…I've actually never been in a relationship",
            "Make a left then right..ME: makes a U turn",
            "When they THOUGHT u were done arguing then u mumble something from the other room",
            "Calling me a liar when I took my time to make up the story makes me soo madd!",
            "He’s showing u all his red flags but ur favorite color is red so VIBES.",
            "If anyone needs their toilet flushed 137 times, my kid is available.",
            "I'm going to call u, or at least text u waaaaay after the fact",
            "Uhh sry was watching TikTok videos, what'd u say?!",
            "I been cutting the same dude off for 10 years now..I hate this man",
            "I'm almost there is not a lie, I am mentally about to get ready to physically be there",
            "Don't make eye contact, not gonna make eye contact, God forbid they think I'm listening",
            "Me waking up to relive the same day ive been stuck in since March 2020",
            "Nope didn't get ur message, I got an iPhone, let me make sure I do those damn updates",
            "Nodding is the best substitute for listening, I don't be knowin nothing they said LMAO",
            "When the song hits just right so it goes on repeat until u're sick of it",
            "I've only slept with like two people, not claiming the rest",
            "Sry, I'm thinking of something else to think of instead of listening to u",
            "My 12th time starting this diet, this time will be different",
            "My bro really loves you, I've never seen him act this way over a girl",
            "After I say 'that’s crazy' Twice im done listening, JUST stop LMAO",
            "I have slept so much in the last 3 weeks that my dreams are repeating",
            "I'm around the corner..ME: Still in the shower",
            "Don't forget the onion rings…ME: brings back onions and ring pops",
            "I'll only try 1600 times, after that u're officially cut off",
            "I live like 3 different lives, its LIT LMFAO",
            "When u forget their name after.0023 seconds",
            "Ima keep switching partners if they keep doing sh*t I don't like",
            "I'm not a person u should put on speakerphone.",
            "When someone explains something to u three times and u still have no idea what's going on",
            "I never meet new men, I either get back with my ex or my ex ex man",
            "I just wanna wear it right quick. I'm a give it back. I got my own hoodies",
            "Why aren't u listening to me? ME: bc I'm choosing to hear no evil today."
        ]
,
        "CancerButton": [
            "Home is where the heart is, and my heart is always in my cozy sanctuary.",
            "Sentimental? My keepsake box is a treasure trove of memories.",
            "Intuition? I trust my gut feelings more than anything else.",
            "Family time? My calendar is blocked for quality bonding moments.",
            "Empathy? I've got a radar for everyone's emotions, even the cat's.",
            "I ain't friendly, I don't give af if my friend is speaking to you. Don't look over here.",
            "People be like you need to get a bigger TV... How about you get your own place to live?",
            "How are you mad at me because you like my man?",
            "Before you do, can you NOT.",
            "You mean to tell me you want to be a cashier your whole life because you want to stay on Section 8?!",
            "We're outside this summer, BUT I'm bringing my EX.",
            "Can you just breathe over there.",
            "How the heck are you 40 plus with no bank account or driver's license?!",
            "I stayed until I hated you... don't ever second guess my loyalty.",
            "She can't break your heart if you don't ask her out.",
            "You're in your mom's basement, on social media talking down on people who are above you? I don't get it.",
            "I'm bored when my man is with his wife at home.",
            "When you intentionally sit by yourself, somebody sits by you because 'you look lonely.'",
            "Do NOT give life advice if you have never left your hometown.",
            "Here I am back with this man after the 20th breakup this week.",
            "When I come to class and see someone sitting in my unassigned seat... UGHH.",
            "You all do know there is a whole world outside of your neighborhood box you live in, right?",
            "When the ex tries to win you back during a custody exchange at the local park.",
            "I can’t decide if it's your aura or your face, but just no.",
            "I will never date someone who thinks going to Miami is 'well-traveled.'",
            "She broke up with me, so I'm channeling my inner Taylor Swift and am going to top the charts.",
            "I'm an introvert, so go be happy somewhere else, please.",
            "The nerve of this guy to ask me to sleep over with him at his MOTHER'S house.",
            "Yeah, I'm supposed to be on a diet but… fries. Maybe next year.",
            "When I leave you alone, please leave me alone back... Thanks.",
            "I can't argue with someone who can't keep track of their birth certificate.",
            "We're broken up but still sleep with each other every weekend.",
            "I’m channeling my 2005 high school mood right now, so just stay over there and no one gets hurt.",
            "You've never left the USA but call yourself a 'Passport Boy'?.. Make it make sense.",
            "When he breaks up with you, so you buy his cologne and spray it on all your stuff so no one gets suspicious.",
            "I’m not mad, you just need to stop breathing, that is all.",
            "Don't approach me if you don't know your social security number.",
            "I left him but he's trying to hang on to me tighter than Jack hung on to the door.",
            "When he got food for himself but not you even though you said no, so you ignore him and eat half the fries.",
            "You gotta be a bold MF to wake up and smoke weed with NO JOB.",
            "Friends talking about 'leave him alone'... I will leave Y'ALL alone TF."
        ],
        
        "LeoButton": [
            "Buying SECTIONS in the club when they on SECTION 8 is crazy",
            "Spotlight? Just follow the crowd's applause; I'm the center of attention.",
            "Drama? Life is my stage, and I'm the star of every scene.",
            "Generosity? I give, and people can't help but love me for it.",
            "Confidence? I'm not just self-assured; I'm practically radiating it.",
            "Roar? It's not just a sound; it's my majestic presence announcing itself.",
            "They ask me why I talk to myself, I tell them because sometimes I need to speak with a professional.",
            "I thought being in a relationship with a liar was bad, until I met a b*tch who only told the truth.",
            "When someone doesn't answer my call within the day, I don’t answer their call for a year.",
            "Thinking about exercise should sooo count. It's a brain exercise.",
            "“So..am I the only girl you’re talking to”..ME: yeh, everyone is asleep already.",
            "I'm a strong independent woman but you need to buy me flowers and attend to my emotional breakdowns.",
            "I don't care if people like me as long as they keep pretending that's all that matters.",
            "I might be broke but this face card NEVER declines.",
            "*police takes my mugshot* my insecure a*s: let me see.",
            "I don't call anyone my ex, I call them the deceased. How could they live without me.",
            "Not even gonna front, I really do think I’m all that and a bag of Fritos, HOTT Fritos.",
            "Staring in the car window dramatically singing to Adele then realizing you took the tint off.",
            "A job job is not cool, they have an app for that now.",
            "Our first argument you better be outside my house with a boombox and roses.",
            "Me: Runs for 2 mins. My heart: If you don't stop, I will.",
            "Of course I wasn't taking you seriously, you were supposed to take me seriously though.",
            "If you see me on multiple dates do a b*tch a favor and let me know who looks better on me.",
            "“Haven’t heard from you in 59 minutes, have a nice life.”",
            "Forget exercising, filters are way more effective method of toning.",
            "Of course they didn’t invite me to the party, I’d take all the shine.",
            "Watch as I dramatically swipe everything off the table to make room for a giant map to explain the plan.",
            "I love giving my man hell and he doesn’t leave me, you love it here huh babe?",
            "I’ll walk into a whole event and only speak to people I like.",
            "Reservations are so embarrassing like 'hi, I'm here for my spaghetti appointment.'",
            "I'm single because people don't know how to swipe right literally.",
            "If you don’t get my name tattooed across your forehead then I cannot take you seriously.",
            "My life feels like an opera. Lots of high-pitched screaming and I've no idea what's going on.",
            "Him: that s*x was so good bae. Me: yes, I'm aware bro. Me…share a man?? Is it crack you smoke?",
            "Is that a chicken wing? Ew low vibrational food.",
            "There's no moving on from me, it's either ME or GOD.",
            "I hate a man who knows his worth..wtf you mean I can’t cheat on you.",
            "Here's to My b*tches Who Use Tea Spoons for Everything because Big Spoons Give Them Bad Vibes.",
            "I would have lots of friends if they didn't come with so many side effects.",
            "Buys section/bottles in a club… 'Please stay away from my property.'",
            "Yes okay I will get over it, but I have to be dramatic first."
        ]
,
        "VirgoButton": [
            "Did you see that organized closet? Yep, that's my masterpiece.",
            "Perfectionism? I'm not obsessed; I just want everything flawless.",
            "Routine? My schedule is a work of art, down to the minute.",
            "Detail-oriented? I spot what others miss; it's a gift and a curse.",
            "Analyzing? I can dissect a situation until every angle is explored.",
            "I'd like my coffee with a pinch of sugar, & brown color #D3E554",
            "'Wrong bch' really irritates me. An Organized man like myself would never mix up my h*es",
            "I use to bring my tv remote to school thinking it was my calculator.",
            "I only asked for 12 sprinkles, why is there 15?!",
            "Types of vacations I need: a week to deep clean everything I own, twice.",
            "Hit's curb, scrapes the brand new chrome rims & giggles like it's funny.",
            "I only date guys that have electric cars, I'd be damn if I pump gas.",
            "Types of vacations I need: a week to just sleep, then sleep some more.",
            "WHOPPS! DID I DO THAT?!",
            "Talking about I only eat organic, with all that BUTT u be eating.",
            "Sometimes I'mma just agree with everything u say & let u be wrong.",
            "When u get into a heated argument, realize u're wrong & now u initiate the break up.",
            "I'm a very picky eater, I only eat human food.",
            "Me: If I'm withdrawn but reliable & they'll see the real me. Also Me: God why does everyone think I'm a psychopath.",
            "I got rid of all my white clothes, im sick of looking like I peed my pants.",
            "Girls say I'm too picky and unrealistic when it comes to women, yet u keep taking filter pics that grab my attention.",
            "Types of vacations I need: a week where I don't speak to anyone.",
            "When I face even the slightest obstacle in my life, I call my parents.",
            "Manufacturers are such liars, I weighed a bag of chips and it was way off from the weight on the label.",
            "I think i might be the saddest happy person and the meanest nicest person to ever exist.",
            "Ya'll drive on E, I drive on F.",
            "I swiped left to the end of tinder not one freaking cute girl.",
            "If this sign says \"first of all\" Run away bc they've prepared research, data, charts and will destroy u.",
            "When u flush ur Airpods down the toilet.",
            "When u don't let any little detail slip by.",
            "I'll show up to work on time when u pay me for my time.",
            "My wife is mad at me for breaking the dishes, but it’s her fault for making me clean them.",
            "When someone says 'it's just a minor detail' and u're like 'NO, it's a Knit-picky!'",
            "Nobody: calm down Me: I was calm before u said that now I wanna choke u.",
            "When u break something and fix it enough that the next person who uses it thinks they broke it.",
            "I'm either too direct or don't express my emotions at all... there's no in between.",
            "Them: u're so quiet in person. Me: My spirit doesn't like u.",
            "When the doctor gave u 3 weeks to live so u rob a bank and the judge gives u 20.",
            "Do I want space or attention? One will never know.",
            "If u think i'm mean, u should hear the voice in my head.",
            "GOT SO HIGH I ASKED GOD TO UNHIGH ME."
        ]
,
        "LibraButton": [
            "Decision-making? Let's consult a committee before I choose.",
            "Balance? It's not just a yoga pose; it's my life philosophy.",
            "Harmony? I'm like a mediator superhero, always restoring peace.",
            "Social gatherings? I orchestrate events like a seasoned conductor.",
            "Flirting? I'm not just charming; I've mastered the art of attraction.",
            "BLCKEDDD UNBLOCKEDD CUSSED OUT BLOCKED AGAIN",
            "Life be simpler when u nonchalant, soon as u start chalanting sht go left",
            "I be praying then randomly think about what ima eat for breakfast tomorrow",
            "I hate when girls say I'm Indecisive, btch I ghosted u, decision made",
            "If the party is full of people with no license or bank accounts do NOT invite me!",
            "Them: Hey. My name is Jonny ME .01 secs later: dam, what was his name again",
            "Being indecisive ain't so bad, I dispute every purchase & it pays off",
            "u got .0102012 secs before I cut u off, come CORRECT!",
            "I study for 5 min then find myself on youtube watching a series about Street Food in Tijuana",
            "Sucks that I can't stick with one solid excuse to call in to work",
            "They out here eating low vibrational food, take me home please",
            "I was going to make a joke about procrastination, but I kept putting it off",
            "I asked my girlfriend what she wanted for dinner. I’m 35 now and still waiting.",
            "If I see a dude with black air forces walk in, I'm leaving IMMEDIATELY!",
            "Me: I'm going to focus on this task... My Brain: get somebody else to do it!",
            "Do I vote for the person who actually knows what they're doing or one who won't get me canceled?",
            "U not about to fight my girlfriend looking like the girl version of mike tyson",
            "After my 3rd 'That's crazy' please stop talking",
            "Dating me is like knowing if the ice cream machine is working at McDonald's so choose wisely.",
            "When someone wants to argue, just smile and nod, then slide in their man's DM",
            "Ya'll ever been so drunk u forget to have s*x",
            "I go outside I regret it, I stay in and wish I was out, I need HELP",
            "When in doubt, smoke an L",
            "Once I hit 30+ I be having to calculate my age counting up from my birth year",
            "Do I sign up for FeetFinder or work at Walmart?",
            "When it comes to conflict, I'm an expert at avoidance",
            "Looses custody of kids, goes out on Saturday night like nothing happened",
            "Do I make a paycheck today or do I give my paycheck to Netflix",
            "I have zero friends with short hair. Don't need any of that Karen sh*t going on.",
            "I heard playing jigsaw puzzles helps with concentration, so I binged all the Saw movies",
            "To have or not to have kids. More like to pee or never pee alone again!",
            "I stay home bc if the world comes to an end I need to know where my towel is",
            "Tryna learn more skills, but YouTube tutorials always lead to binge-watching shows I've already seen",
            "Should I buy these eggs or pay for gas?",
            "I stay off of Tinder bc creepers",
            "I've mastered looking people in their face and not listening to anything they said"
        ]
,
        "ScorpioButton": [
            "Secrets? They're safe with me. I'm like a vault of mysteries.",
            "Intense? My emotions run deep, and I don't hold back.",
            "Detective skills? I can uncover the truth even in the shadows.",
            "Passion? It's not just a word; it's the fire that fuels my every move.",
            "Transformation? I embrace change like a phoenix rising from ashes.",
            "I just made this man confess some sh*t I made up in my head",
            "I'm soo scared to get my feeling hurt again cause I promise ima be on the news",
            "If u cheat on me while I'm being a step mom. I'm leaving ur kid at the park",
            "This would have never happen if u never caught me cheating",
            "Would u like a pic? F*ck is u staring at?",
            "When u get ur revenge, don't forget to take a selfie!",
            "When he says he doesn’t want a relationship but gets mad if another man walks within 10 ft of u",
            "UMMM CAN I HELP u?!",
            "Boss won't cover my shift so I'm not covering his affair.",
            "I need to control ur life so this relationship can work",
            "IF BLACK AIR FORCES WERE A PERSON",
            "Revenge is a dish served with a side of satisfaction.",
            "I'm never leaving a club early again in my life, I'll even help them cash up.",
            "u ARE NOT HIM!! MORE LIKE HER LMFAOO",
            "It still bothers me that I didn’t cheat on my ex",
            "I make sure the s*x is trash so I can make sure u like my personality like u said u did",
            "I NEED A RUFF NECK..BARK AT ME DURING S*X",
            "He cheated so I texted every girl he knows and told them they need to get tested.",
            "For someone who keeps saying 'it is what it is' I honestly have no idea what it actually is",
            "Even look at my dog wrong and I'll go John Wick on u’re a*s",
            "She slept with my best friend so I slept with her mom and now I'm really her daddy.",
            "Not to be dramatic but the sun setting at 5:00 pm every day has ruined my life",
            "Sometimes I get road rage walking behind people at the grocery store.",
            "I be wanting to tell people happy bday but I never got one so fk it",
            "I spend money like it'll solve my problems",
            "If we break up, I do not wish u well. I hope u get chased by hyenas",
            "My girl left me so I told her dad I'm the better daddy.",
            "Why does asking for money back that ur owed feel like a crime",
            "Being around me is fun n games until my attitude is activated",
            "My boyfriend cheated so I moved in next to him so he can hear what I meant by go faster.",
            "Don’t hit me up after ur little relationship didn’t work out",
            "I LOVE u, But F*Ck u",
            "If he cheating, cheat back. Support ur man in everything he does.",
            "Don't worry babe, yeah we use to FK but we just besties now",
            "I'll commit crimes before I commit to a relationship",
            "The bishop excommunicated me for cheating on my husband so I slept with his wife."
        ],
        
        "SagittariusButton": [
            "Wanderlust? You bet! My passport is always ready for an adventure.",
            "Philosophy? I ponder life's big questions while others are still waking up.",
            "Optimism? I'm not just hopeful; I see the silver lining everywhere.",
            "Adventure? My bucket list is as long as my tales of epic journeys.",
            "Freedom? I can't be caged; I'm the free spirit of the zodiac.",
            "I be on vaca waking everybody up before sunrise, stay home if yo a*s wanna sleep",
            "Dating me is not for the weak, I make up random stories in my head and bring up issues from the past",
            "I beep the horn loud af outside my sneaky link crib for excitement",
            "I make weird noises & yell out random movie quotes",
            "I hate it when I'm singing a song & the artist gets the words wrong.",
            "My wedding cake gonna be an edible & I'm not warning anybody",
            "Drunk by 2 am, work by 7 am, a responsible drunky",
            "When the pole dancer turns around and she’s pregnant LMAO",
            "I AIN'T GET SLEEP CAUSE OF Y'ALL, Y'ALL AIN'T GETTING SLEEP BC OF ME!!!",
            "I nap for your protection, not mine. I can go ALL DAY!!",
            "Got to stay off indeed. I got an interview at NASA tomorrow",
            "When your joke is bomb & you gotta wait for the squad to settle down",
            "If you're still waking up after 9 am, YOU ARE A MANCHILD",
            "This morning I was in love, tonight I'm for the streets",
            "When you purposely don't stop the microwave before it reaches 0:00",
            "I noticed you're taking a nap in the middle of the day without an alarm... I too like to live dangerously",
            "So my therapist retired today. I still need help but hey at least he's happy.",
            "THIS NI99A WISPER SOUNDS LIKE A GROWL",
            "I love my ambitious hubby but the ER bill is getting a little too high.",
            "Today I am He/Him. Tomorrow She/Her. Friday I'm both",
            "Some of y'all need a mute button",
            "We all have that one friend that is up at 4 AM trying to take over the world.",
            "When the priest asks to be in the puff puff pass circle",
            "I sound like a dolphin when I sneeze",
            "I will ruin your day at 6 am sharp IDC!",
            "All I asked for was one threesome. now the 3 of us have a wedding scheduled in Vegas",
            "My friends don't like to bring me nowhere, they say I'm too LOUD",
            "That friend that calls before 8 AM wondering what you're up to",
            "When the weather is more predictable than her mood.",
            "I TALK IN ALL CAPS!!!",
            "The FDA says 400 mg of caffeine a day is where I should stop but the FDA doesn't own me.",
            "When she takes anal better than the guys in your unit did.",
            "I can sneak a midnight snack for sh*t, I always end up trippin on my way to the fridge",
            "When they're on Adderall but you're on Valium",
            "I went to prison one time. Now I have a soap saver and an infected mom tattoo.",
            "My upstairs neighbors stomp to get me to stop my music, but I just dance to the beat."
        ],
        
        "CapricornButton": [
            "Goal-setting? I don't just climb; I conquer mountains.",
            "Ambition? My dreams have a GPS, and I'm heading straight there.",
            "Workaholic? It's not just a job; it's my legacy in the making.",
            "Responsibility? I'm the reliable one people turn to in any crisis.",
            "Discipline? I'm not just organized; I'm a master of self-control.",
            "I smell so good you're gonna moan a little when you hug me.",
            "I'm sorry but 3 or more kids in your 20s is crazy.",
            "I'll share my location with my boyfriend & still cheat, I don't give a f**k.",
            "I'm not saying you're a bad person, you're just not as good as me.",
            "These men in my DM's be BROKEEE.",
            "You THOUGHT I WAS FEELING you?! you LOOK LIKE A MUTT.",
            "Oh, you're vegan? I didn't ask, but thanks!",
            "It feels so good to be 0 weeks pregnant.",
            "Boyfriend cheated, so I got pregnant by his stepdad.",
            "Every time I taste my cooking, it just assures me I'm wifey material.",
            "Going out with heartbroken people is LIT. These mfs drink to DIE.",
            "Go disappoint your Momma, NOT ME.",
            "I'M REALLY HIM!! I'M THAT GUY.",
            "She done sent me 5 attachments. Each one uglier than the last.",
            "Dudes be asking where the b*tches at but never look within themselves.",
            "I'm getting a little jealous vibe from you! Am I right?",
            "Never would I date someone with an STD, been there, done that.",
            "Fat people always got something to say... now if I say something back, then I'm wrong.",
            "I already have my complaint forms pre-signed.",
            "I feel sorry for married people, single & miserable is so much better.",
            "If we don't work out, that's cool, but don't ruin my chances with your friend.",
            "Linda got a tattoo. Guess no heaven for her.",
            "If you ate a man's bootie, you should try Fear Factor.",
            "I might not cheat but I know who's next for sure.",
            "When the vegans yell at you for breathing their clean air.",
            "Yes, I judge people with multiple baby daddies... FIGHT ME!",
            "I'm taken when he's around, single when you're around.",
            "I'm better than you. I'm a child of GOD!",
            "You can't cook? We can't date. PERIODT!!",
            "THEM: You single?? ME: Sometimes, why?",
            "When your aunt says you need to do better but she's on her 5th marriage.",
            "Love it when I see my ex dating Gargoyles LMFAO.",
            "You look like a 'Monday' morning LMFAO.",
            "Gross, you smoke weed? - pops another percocet.",
            "When you hate people more than the virus.",
            "THIS SIGN IS FOR THE STREETS!!"
        ],
        "AquariusButton": [
            "Rules? I'd rather invent new ones and see where they take us.",
            "Innovation? I'm not just creative; I'm a visionary thinker.",
            "Humanitarian? I can't help but fight for a better world.",
            "Rebellion? It's not just a phase; it's my lifelong outlook.",
            "Individuality? I march to my own beat, and the parade follows.",
            "When you tell her 'NOT TODAY' and she instantly starts imagining life without you.",
            "I'll never tell him this, but sometimes my man be making a lot of sense.",
            "I ghost people because I fall in love quickly.",
            "I say 'I love you' on the first date.",
            "When you try too hard to fake a smile.",
            "I imagine fake scenarios & just end up hurting myself.",
            "Thanks to buy now, pay later I now basically have another car payment.",
            "Please give me space but also attention.",
            "I hate when people raise their voice; then I have to cry.",
            "20 minutes after ordering a package online… ME: Where ya'll at with my package!!!",
            "Me in the work bathroom giving myself a pep talk about not to quit out of anger.",
            "When I say 'be safe,' I mean that from the bottom of my heart.",
            "When someone is getting attached too early… Hmm yes baby I like you.",
            "'If you're waiting for me to message you first, we will never talk.'",
            "I will literally cry if I find out you ate already without me.",
            "I stop myself from being rude so many times a day and NO ONE appreciates it.",
            "I only fight with someone when I know I'm right. I be fighting a lot LMFAO.",
            "When he says 'I'm so glad you're not one of those crazy girls' LMAO.",
            "WTF is a 'talking stage'? Like, I want your soul NOW.",
            "I said No but I really meant ABSOLUTELY NOT!!",
            "My biggest toxic trait is I know how to love but I don't know how to believe I'm loved.",
            "I'll ask once, more than that feels like begging.",
            "When you agreed to go out and the time to go out is getting closer.",
            "Now... let me find the perfect song to cry to.",
            "TF is 'taking things slow'? Put me in your WILL.",
            "Sleeps after a long day of ignoring their feelings and pretending to be heartless.",
            "He getting me drunk to get some but jokes on him I'm about to start crying.",
            "I hate baby steps, let's get Married.",
            "That was a worse idea than when I got back with my third baby daddy.",
            "Nothing hurts more than when you send a meme to someone and they already seen it.",
            "When you finish a good book & need everyone you know to also read it asap so you can discuss.",
            "Somebody: you can't touch cactus, it'll hurt too much. Me: Hold my feelings.",
            "When you realize your eraser dies slowly because of your mistakes.",
            "Ladies, if a man says he will fix it, he will. There is no need to remind him every 6 months about it.",
            "Me, getting ready to make the same bad choice again",
            "Every time I let someone in they disappoint me."
            ],
        "PiscesButton": [
            "Dreams? I dive into them and swim in my imagination.",
            "Intuition? I sense things others miss, like a psychic without the crystal ball.",
            "Empathy? I feel for everyone, even fictional characters on TV.",
            "Creativity? I'm not just artistic; my ideas come from cosmic inspiration.",
            "Daydreaming? It's not a distraction; it's where my magic happens.",
            "How u accuse of me cheating, whole time u had more side pieces than KFC",
            "I date broke boys so I can control them..act right or gimmie that $10 back!!!",
            "I don't actually exist so if u ever met me it was a prank",
            "Some of ya'll should require to take IQ tests before birthing a human",
            "Goes to strip club with tax return check: 'u know I can take u away from all of this right?'",
            "When u try to start a fire with wet wood",
            "The fact that I've NEVER cheated is pretty dam impressive",
            "The weed man has a family to support too, that's why I buy",
            "My sexual intercourse body count resets every year",
            "I can't belive u canceled plans that I never intended on showing up to",
            "I love to hear people's problems, it's the only reason I read dating profiles",
            "Saying bye Felicia is way more considerate than ghosting dont u think?!",
            "I got covid, food was tateless for a week, might as well have gone vegan",
            "Instead of proposing to my girlfriend,  I'm going to introduce her to my divorced friends",
            "Last night I tried fixing my car with duct tape",
            "I hope u know masturbation is sex with demons",
            "I landed me a sugar baby ya'll..All he needs is help with his homework",
            "I don't like people in real life, but I'm going to like everyones post on Facebook to be nice",
            "Next time u bring ur man on the girls trip, he has to sleep with one of us",
            "I took one for the team when I got married. America u're welcome",
            "Damn, did I forget to cry today?",
            "I got $100 for anyone who hasn't flirted with more than one person this year",
            "The hacker has bills to pay too, that's why I use easy-to-guess passwords",
            "I don't procrastinate. I wait until the last minute to do things bc I will be older and n wiser",
            "Obviously the person who created mirrors did it to be spiteful to ugly people",
            "I love to hear people's problems, it's the only reason I volunteer at the crisis hotline",
            "I love u as passionately as my emotion-dulling medications allow",
            "Good men aren't hard to find, u just don't fit the description FIONA!",
            "Sure, u can borrow my car for ur bank robbery, u need to get there safe don't u",
            "My emotions are as unpredictable as the price of gas",
            "If u owe me money the only thing u should be eating around me is ur fingernails",
            "I'm the realationship expert who hasn’t been in a relationship",
            "Ghosting someone for just a few days and returning as if nothing happened",
            "u accused me of being untrustworthy, but the whole time u had more secrets than the CIA",
            "I love the 3 am version of people. Vulnerable. Honest. Real.",
            "I need u to text me every 30 seconds saying that everything is gonna be OK."
        ]

    ]
    
}
