//
//  UpgradedJokes.swift
//  WhatZodiacSignIsThis
//
//  Created by MyMac on 10/28/23.
//

import Foundation
// A jokes dictionary that will accept a String for the key and an array of Strings for the values
struct UpgradedJokes {
    
    static let shared = UpgradedJokes()
    
    let upgradedJokesArray: [String: [String]] = [
        "AriesButton": [
            "I don't wait for elevators; I take the stairs. Who has time to stand around?",
            "New restaurant? I'm there! I live for taste adventures.",
            "Sports? I don't just watch; I compete with the players from my couch!",
            "Personal trainer? Nah, I'm the life coach of my own journey!",
            "A rock band? Count me in! I've got enough energy to light up a stadium!",
            "If u ain't making 6 figures BEAT ITT!!!",
            "Dumb sh*t irritates me like people clapping when the plane lands",
            "One red flag & I'm Casper the ghost. You will not see me",
            "When u talk & people are playing with their phones so u cut the WiFi",
            "If I order a burger with no onions & u add them, don't be shocked when I fake an allergic reaction",
            "I get drunk and start buying drinks for total strangers",
            "I really need to stop buying stupid things when I get paid",
            "I've got 99 problems and 86 of them are completely made-up scenarios in my head",
            "Quit my job this morning..started only fans this afternoon",
            "Pretending to be listening but actually planning on when to interrupt u",
            "Don't tell me good morning, that's for me to decide",
            "I get hurt & immediately go into hustle mode",
            "5'5 and under?! Ew, no thanks leprechaun",
            "Patience shorter than ur gf ponytail",
            "It takes me .001 sec to pick out my clothes for the day..I truly dgaf",
            "Bring back saying 'take a hike.' It's so wildly dismissive without being vulgar",
            "If I request a Lyft and u can't be here in 5 mins don't bother showing up",
            "Once she falls in love, I fall out of character..and CUT!",
            "If I offer u food DO NOT accept it, I was being fake nice",
            "It grinds my gears when y'all talk with crust in the cracks of ya'll mouth",
            "I talk to people in their native accent, I just can't help it LMAO",
            "What if I told u explaining something with a clever metaphor doesn't make u right",
            "Sometimes I wake up, hear y'all breathe and get pissed off",
            "I may make impulsive decisions, but at least they're never boring",
            "Meet my friend dial..TONE..clickk!!",
            "I can't stand a know-it-all..bet u ain't know I slept with ur man haa!",
            "Once we break up… 'Hello, 911..I'd like to report a drug smuggler'",
            "Are those cloth interior seats? LMFAO",
            "I'm not stopping at two red-lights in a row, the first one counts for both",
            "Once temp reaches 70..hoochie daddy shorts in full effect",
            "Ur man this, ur man that. Ur man stays in my DM!!",
            "As a grown man, why are u wearing a bob? that infuriates me",
            "Just bought a house without inspection. A gang of roaches just asked for the 1st month's rent",
            "If I'm too much, then go find less",
            "EAT IT or BEAT IT!!",
            "Invested my entire savings in crypto..now I can't even afford super mario coins",
            "Princess treatment or kick rocks SIR",
            "I think walking texters are worse than drunk drivers. Don't walk and text",
            "Took a loan out w/out reading the fine print. Tell me why the terms say 'for a lifetime'",
            "I ain't reading all that…I'm sorry that happened tho",
            "Why can't u have ur funeral on a weekday so I can skip work and not mess up my weekend",
            "I don't believe in second guessing, only in doing and regretting later",
            "I wish people had MUTE buttons",
            "If I want advice I will ask Siri or Google, the same place u get it from",
            "I make decisions like a toddler, fast & irrational but always with good intentions",
            "Don't call me to vent, my life f*ked up too",
            "When someone says 'Give me a minute'..an hour later",
            "First day as a construction worker, I quit before lunch…they out here playing Jenga with cinderblocks",
            "Is there a way to block someone in real life?",
            "When I get ready to take a picture and none of them come out good I be furious",
            "If I don’t get a text back I just assume u must be suckn d**k",
            "NO we did NOT date, u were a childhood friend SIR",
            "Me at 3am reading all the 759 comments of two people arguing",
            "I texted u at 4:01..it is now 4:02 and 35 sec later..have a nice life",
            "If I have to wait on line then please don't invite me to the function",
            "Call me biodegradable because I break down really easily",
            "Applied for every job I saw on indeed..now I'm in an interview in a warehouse but a** naked",
            "Learn how to wash ur back properly before approaching me",
            "I know everything happens for a reason but what the fk",
            "She told me she's respectful, loyal & cooks..i told her the engagement ring will be ready tomorrow",
            "I don't care what u think about me, I don't think about u at ALL",
            "Got a list of people I want to punch in the face",
            "One argument.. ME: I think its best we go our separate ways",
            "Is there an age limit on stupidity?!",
            "I'm living in the moment and it's horrible",
            "Coughs twice... ME: somebody call the ambulance",
            "Chat GPT this, chat GPT that; ask chat GPT when tf my tax return coming",
            "I set my alarm to ring every 5 minutes in the morning, I still be late",
            "I hear one random spooky noise at night and I'm moving in with my mom",
            "Ya'll really need to stop with these podcasts, somebody used their pet monkey as a co-host",
            "Small things turn me off..bc why are u 30+ with no ID",
            "I get hurt once and cheat on everybody and their momma",
            "Don't ask me about being single at Thanksgiving, worry about ur 4th divorce aunt Riley",
            "Side streets will always get plowed last. ur mom will continue to get plowed first. That won't change.",
            "Wearing boxers at this big age = DATE CANCELLED!",
            "My dumb*ss be browsing my emails in the club",
            "My momma may have raised an alcoholic foul-mouthed a*shole but she ain't raise NO btch",
            "One minor inconvenience and I call my dad on speed dial",
            "I like to wear my headphones with no music playing to avoid people",
            "The early bird gets to cry for a little bit longer in the work parking lot.",
            "Won my first game of blackjack..bet my savings on the 2nd  game and lost..I can't breathe ya'll",
            "Fool me once, shame on u; Fool me twice I f*ck ur crew :)",
            "If u drive slow maybe consider using the sidewalk or  emergency lane",
            "Got my first speeding ticket.. street credit just went up, I'ma start rapping",
            "Ya'll bond over gossip, meanwhile ur own life is in shambles",
            "I'm not sure which pisses me off more waiting on my girlfriend or a slow website to load",
            "U got one more time to ignore my call before I show up at ur momma's house",
            "How u talk down on people above u?!",
            "Trying to talk to someone at a concert makes me want to learn sign language.",
            "Barber pushed my hairline back..I called the state board..License ReVOKED buddy!",
            "Work calls before I've had my coffee??..I think TF NOT",
            "Church bells waking me up in the morning make me long for the coming of the antichrist",
            "My crush rejected me, so I reject sobriety",
            "No guy can impress me, I have tried apps that allow me to generate my perfect man and it says error try again",
            "Stores don't allow pets, but bad a*s kids are welcome to run freely",
            "Risking is better than regretting",
            "'U blocked me?'..Um yah, we f*cked, it was trash..done deal",
            "Ok u don't open doors or pull out chairs but at least let the toilet seat down",
            "Avoid the embarrassment and don't DM me. Thanks!",
            "Not flushing the toilet is the worst form of littering"
        ]

,
        "TaurusButton": [
            "Buffet? That's where I set up camp, sampling all the delights.",
            "Puzzle? I won't quit until every piece finds its place!",
            "Movie night? Classic films, cozy blankets, and my comfort zone intact.",
            "Gardening? I'm in. The patience for growth runs in my roots.",
            "Umbrella? Always ready. I'm the dependable one in every storm.",
            "I completely restart my PC after a Zoom call; I refuse to be caught lacking.",
            "Monday again, time to get to this job, be fake & act like I like people.",
            "If I finish washing dishes & forget one, I'm throwing it out.",
            "I even keep my family out of my business; they'll talk about u too.",
            "I'm already on my like 3rd life. Don't make it 4!!",
            "When your plan is canceled & you can stay home all night like you wanted to all along.",
            "No one will know where I live; meet me at the gas station LMAO.",
            "I'm not insecure, just not with all that friendly sh*t.",
            "Why would I drive 3 min away for pickup when I can order Uber Eats for $79.95.",
            "How do you know my full government name? Who sent u?!",
            "I gotta stay high; people are annoying.",
            "You don't need to stay in bed all day said the weirdo.",
            "Don't ring my doorbell if you didn’t set an appointment.",
            "Yes, I'll meet y'all there!... ME: knowing damn well I'm not going.",
            "HMMM GET SOMEBODY ELSE TO DO IT!!",
            "Knowing your worth will have your phone dry af.",
            "Looking at the menu even though they're going to get the same thing as usual.",
            "I have eaten 22 times and taken 13 naps and it's still today.",
            "My cup was placed on the table at a 90-degree angle and now it's at 40... who's been in my house?",
            "Don’t ask me why I'm single... I need money, not love fool.",
            "I'm not a hoarder; I'm just sentimental about my stuff.",
            "Sitting back & watching things happen they said would happen.",
            "Do NOT breathe heavy around me; I already don't like people as it is.",
            "Doing nothing is my biggest hobby.",
            "I'm a thinker so make sure all your sh*t adds up before I start calculating.",
            "I'm half extroverted, half introverted. I like to hang out and then spend days alone to recharge.",
            "I need a vacation to recover from my vacation.",
            "If you see me looking zoned out it's because I'm having a therapy session with myself in my head.",
            "U got IG? NO... FB? NO, What's your name? NO.",
            "One of the FREAKIEST AND NASTIEST people you'll ever meet IF I like u.",
            "WHO ALL GON BE THERE?",
            "Now why u invite me out knowing there would be people in the public?!",
            "Scared to get your heartbroken? break theirs first.",
            "I check ID's and baby pics now; these surgeries are getting out of hand.",
            "The ULTIMATE Homebody.",
            "If I run an errand, that is considered going out... argue with ur mama.",
            "Can I see u?? Um, see me for what exactly?",
            "Me hiding in my house recharging my introvert batteries after too many social interactions.",
            "Every corpse on Mt. Everest was once a highly motivated person, so I don’t feel bad doing nothing.",
            "He's been way too happy; let me check his social media pages.",
            "If I ever disrespected u, I meant that sh*t, because I let u slide 500 times before I did u like that.",
            "Trying to romanticize life while sitting on your bed and eating snacks all day.",
            "I give Uber drivers the neighbor's address & meet them there... you won't know where I live, weirdo.",
            "Hate when I go in public and the public is there.",
            "Get my work done??? Umm, pretty sure it's Friday...",
            "Yesterday u had 200 followers..today 201…who is SHE?!",
            "Me calculating how much sleep I'll get if I watch one more episode.",
            "8-year-old me coughing so my mom thinks I'm too sick to go to school.",
            "If I think you're for the streets that’s exactly where I'll return u.",
            "I'll say I don't GIVE A F*CK and walk away mid convo.",
            "Sex is cool, but have you ever spent hours trying to remember a song name then finally remembering it.",
            "U got one time to be fake with me and you're out of my life for good.",
            "NE1 know what to do while people are singing happy birthday to us?",
            "Lazy? I'm not lazy. I'm selectively active.",
            "I don't trust them farther than I can throw them.",
            "When you're back HAPPY in your own space after being with others for too long.",
            "My bed is a magical place where I suddenly remember everything I was supposed to do.",
            "If you call me and it sounds like we're talking in a hallway, I'm gonna assume you're recording the call.",
            "Now imagine having 7 lazy days per week. How healthy is that.",
            "Saturday morning: I'm going to accomplish so much. Sunday night: Not this weekend...",
            "You must pass a background check as a prerequisite to date me.",
            "Having one 'Lazy day' per week can help reduce stress?? Bet, SAY LESS.",
            "When clothes are too dirty for the closet, but too clean for the Laundry. Meet the chair.",
            "Stop being so loud, these walls are cheap AF.",
            "Instagram please stop suggesting me 'people u may know'. Yes, I know them, but I don't like them.",
            "Life would be so much better if I could just be awake at the right times.",
            "I'm so private, if someone knows my business I know exactly who told them.",
            "Ur trauma made u stronger' NO It did NOT, it made me funnier though.",
            "When u try to be an adult and walk away from an argument, then hear a 'that's what I thought'.",
            "Circle so small I almost cut myself off.",
            "Somewhere, someone's wife has masturbated to me :)",
            "The fact that I procrastinate and still get the job done is the reason I procrastinate.",
            "I don't trust words, I TRUST ACTIONS.",
            "We can chat for a little, but after that u gots to go!!",
            "Literally doing nothing these days, still don't have time for anything.",
            "I don't like anyone knowing anything about me... I wish y'all ain't even know my name.",
            "If u aren't obsessed with me, u shouldn't be with me.",
            "I'm the type of girl that would rather sleep 30 extra minutes than wake up to do makeup & hair.",
            "I am nice, but I am an a*shole, but my heart is big af, but I don't really give af.",
            "Started this year single, ending it single. Consistency is key.",
            "Born to Dance. Forced to Work.",
            "I live in my own bubble, ION care what y'all be doin.",
            "Me ice grilling my mom when my family asks me about something I only told her.",
            "I wanna go out but at the same time I don't wanna leave my room.",
            "Me acting fake distracted when I see someone I know because I don't wanna say hi.",
            "'People say nothing is impossible, but I do nothing every day'.",
            "'Life is full of fake people. Never trust anyone'.",
            "Once u become the cold-hearted person, then no one can hurt u.",
            "Stuck in between of capturing everything in my phone and living in the moment.",
            "'Why are u so quiet?' Nah, I'm actually analyzing each n every one of u.",
            "Just the rising for me today. There will be no grinding.",
            "If I ask u how u doin, I would rather u not tell me how u're actually doing.",
            "Study for 10 minutes. Reward urself with 50-minutes breaks.",
            "Ughh, will there be humans there?",
            "When u wake up a minute before ur alarm goes off and u needed that last minute to make it through the day.",
            "Immediately hating people when u first meet them.",
            "I'm not a morning person, I'm a coffee person.",
            "I came to get this money and leave, not looking for a co-worker friend.",
            "Every day I wake up and plan on doing things, but then I just hold it off for another time.",
            "I hate when people think they know me. Sh!t, my own family barely even knows me.",
            "I'm not an early bird or a night owl, I'm a permanently exhausted pigeon.",
            "I be like 'brb' then go home LMFAO.",
            "Yes, I went on a walk today. May have been from my bed to my kitchen but it counts.",
            "Life on VIBRATION ONLY mode.",
            "'I'll see' = I'm not coming, never was, never considered it.",
            "I’m in an ioslationship.",
            "My bank probably reading my statements thinking 'Does this person not have food at home'.",
            "'Not invited, won't go; not offered, won't ask; not spoken to, won't talk'."
        ]

,
        "GeminiButton": [
            "Texting? I could have a full conversation before you finish your sentence!",
            "Music? I've got playlists for every mood and scenario.",
            "Indecisiveness? I've mastered the art of keeping options open.",
            "Two-faced? Nah, I'm just well-equipped for different situations.",
            "Socializing? I thrive in crowds and can charm anyone within seconds.",
            "I will cheat on u & beg to get back, be good for a week & cheat again",
            "When u pay her rent but she tell social media god made a way",
            "Worst texter alive but a vibe in real life",
            "My 12th time starting this diet, this time will be different",
            "Calling me ur EX is crazyyy…I've actually never been in a relationship",
            "Make a left then right..ME: makes a U turn",
            "When they THOUGHT u were done arguing then u mumble something from the other room",
            "Calling me a liar when I took my time to make up the story makes me soo madd!",
            "He’s showing u all his red flags but ur favorite color is red so VIBES.",
            "If anyone needs their toilet flushed 137 times, my kid is available.",
            "I'm going to call u, or at least text u waaaaay after the fact",
            "Uhh sry was watching TikTok videos, what'd u say?!",
            "I been cutting the same dude off for 10 years now..I hate this man",
            "I'm almost there is not a lie, I am mentally about to get ready to physically be there",
            "Don't make eye contact, not gonna make eye contact, God forbid they think I'm listening",
            "Me waking up to relive the same day I've been stuck in since March 2020",
            "Nope didn't get your message, I got an iPhone, let me make sure I do those damn updates",
            "Nodding is the best substitute for listening, I don't be knowin nothing they said LMAO",
            "When the song hits just right so it goes on repeat until you're sick of it",
            "I've only slept with like two people, not claiming the rest",
            "Sry, I'm thinking of something else to think of instead of listening to you",
            "My 12th time starting this diet, this time will be different",
            "My bro really loves you, I've never seen him act this way over a girl",
            "After I say 'that’s crazy' Twice I'm done listening, JUST stop LMAO",
            "I have slept so much in the last 3 weeks that my dreams are repeating",
            "I'm around the corner..ME: Still in the shower",
            "Don't forget the onion rings…ME: brings back onions and ring pops",
            "I'll only try 1600 times, after that you're officially cut off",
            "I live like 3 different lives, it's LIT LMFAO",
            "When you forget their name after 0.0023 seconds",
            "Ima keep switching partners if they keep doing sh*t I don't like",
            "I'm not a person you should put on speakerphone.",
            "When someone explains something to you three times and you still have no idea what's going on",
            "I never meet new men, I either get back with my ex or my ex-ex man",
            "I just wanna wear it right quick. I'ma give it back. I got my own hoodies",
            "Why aren't you listening to me? ME: Because I'm choosing to hear no evil today.",
            // Upgraded Jokes
            "I done played 'Meeting in my bedroom' 7 times and this bih still in the kitchen",
            "I can smell a b*tch from a mile away",
            "I only use Tinder so I don't have to actually remember my date's name",
            "I will restart the entire song if you talk over it idc",
            "When you realize you have been singing the wrong lyrics your whole life",
            "My deaf senile grandma listens better than my husband",
            "This sign is Liars, Cheats, and Thieves and Everyone Knows It",
            "When he attempts at doing the laundry but puts it in the washing machine and never actually starts it",
            "Dating me is like having a walking monologue that struggles with basic chores",
            "One TV show then it's bedtime. Proceeds to watch the extended director's cut of Lord of the Rings.",
            "The soul of a witch. The fire of a lioness. The mouth of a sailor.",
            "Texts 'Friendsgiving is at 5 pm'... Me showing up at least 2 hours late.",
            "When she says she wants one drink but orders the fishbowl... Twice",
            "Your bank balance is -$200 and wonder why your Amazon purchase won't go through",
            "When your boss sees you out on the day you called out for a 'family emergency'",
            "Talking to my wife is like ordering at a broken drive-thru",
            "Husband said he got a Vasectomy... not according to the newborn but okay",
            "The box of pasta thinks it can tell me what to do so I pour it in before the water boils out of spite",
            "I said I was 9”, I didn't think it was going to get this far.. you like shrimp?",
            "When Netflix suggests you watch a comedy so you watch Chucky because you're the one in charge",
            "She said she was a Virgin. She only works the glory holes for money",
            "The serving suggestion is a SUGGESTION for a reason! IMA DO IT MY WAY!!",
            "When she says she’s single but won't unlock her phone for no one",
            "She blocked me so that must mean I need to hunt her down to make sure she’s okay",
            "My ex-girlfriend said that anal was okay. She never said lube was required. Hence the ex",
            "The water bill just came in so you go out to eat instead because who needs that kind of negativity",
            "I only hang out with guys because they're less drama.. it's only platonic",
            "That flight attendant has no idea what she's talking about. I’m taking a selfie BEFORE WE DEPART!",
            "Just roommates, you mean just f*cking? Got it",
            "My oil light came on 1000 miles ago but the car isn't making any funny noises so I’m good, right?",
            "When he says he's a 'Mormon' but you catch him at the grocery store on a Sunday",
            "When you finally told him what you wanted to eat but he brought you the wrong tacos",
            "When she says she likes espresso but can't handle the mocha choka",
            "I manually input my steps for the day on my step tracker app",
            "BOSS: I need you this hooliday weekend, ME: Sorry flights already booked",
            "I don't do drugs every day, just ones that end in Y.",
            "The expiration date on the milk was yesterday but I'm feeling gangsta today",
            "When he says he loves you but his girlfriend has a ring of death",
            "We need transition lenses that keep getting darker the longer someone is talking to you",
            "She said she wanted a burger then got mad when there were no beans in it",
            "That fake laugh you do when you have no idea what the other person said",
            "The baby daddy who says he’s a good dad but doesn’t remember how many kids he’s got",
            "There is no need to repeat yourself... I ignored you just fine the first time",
            "The baby daddy who says he’s a good dad but he doesn’t remember his kids' birthday",
            "I heard the IRS got funding for tax fraud investigations so... who's moving to Cuba with me?",
            "When you cheat more on your taxes than your diet",
            "When you cheat more on your diet than your ex did on you",
            "I only eat the healthy Cheetos",
            "I only have one girlfriend. H*es on the other hand...",
            "Yes boss, I was in the zoom call the entire meeting",
            "*cough* no officer *cough* that's incense I’m burning *cough* I promise",
            "No, I'm not hungover it's allergies. Yes, I know it’s December, sir.",
            "Drinks a shot of Henny. It’s called hydrating officer. Try it sometime.",
            "No, I do not use porn as melatonin",
            "I told my mom I met a nice girl. I just didn't mention I met her at the strip club",
            "When you’re the one who works but she's a 'strong independent woman'",
            "When she says she’s only buying one thing off Amazon but then you get the credit card statement.",
            "When she says she wears no makeup but her fake eyelash is stuck to her melting foundation.",
            "No babe, him knowing my bra size means nothing, he's just a friend.",
            "When she promises sexy time but pretends to be asleep 5 minutes later.",
            "No officer that is, in fact, my friend's weed in his pants I just so happen to be wearing",
            "No sweetie, mommy’s ice cream is spicy, you won't like it",
            "My boyfriend said he wasn't high but ate an entire pizza, a bucket of cheeseballs, and 6 pickles",
            "I lie so much I start to think it’s the truth",
            "Such a liar, I'm starting to lose track of what I said",
            "Ever met a liar that makes you think you're the crazy one, for noticing THEY're lying.",
            "Why TF are you lying and we’re not even together"
        ]
,
        "CancerButton": [
            "Home is where the heart is, and my heart is always in my cozy sanctuary.",
            "Sentimental? My keepsake box is a treasure trove of memories.",
            "Intuition? I trust my gut feelings more than anything else.",
            "Family time? My calendar is blocked for quality bonding moments.",
            "Empathy? I've got a radar for everyone's emotions, even the cat's.",
            "I ain't friendly, I don't give af if my friend is speaking to you. Don't look over here.",
            "People be like you need to get a bigger TV... How about you get your own place to live?",
            "How are you mad at me because you like my man?",
            "Before you do, can you NOT.",
            "You mean to tell me you want to be a cashier your whole life because you want to stay on Section 8?!",
            "We're outside this summer, BUT I'm bringing my EX.",
            "Can you just breathe over there.",
            "How the heck are you 40 plus with no bank account or driver's license?!",
            "I stayed until I hated you... don't ever second guess my loyalty.",
            "She can't break your heart if you don't ask her out.",
            "You're in your mom's basement, on social media talking down on people who are above you? I don't get it.",
            "I'm bored when my man is with his wife at home.",
            "When you intentionally sit by yourself, somebody sits by you because 'you look lonely.'",
            "Do NOT give life advice if you have never left your hometown.",
            "Here I am back with this man after the 20th breakup this week.",
            "When I come to class and see someone sitting in my unassigned seat... UGHH.",
            "You all do know there is a whole world outside of your neighborhood box you live in, right?",
            "When the ex tries to win you back during a custody exchange at the local park.",
            "I can’t decide if it's your aura or your face, but just no.",
            "I will never date someone who thinks going to Miami is 'well-traveled.'",
            "She broke up with me, so I'm channeling my inner Taylor Swift and am going to top the charts.",
            "I'm an introvert, so go be happy somewhere else, please.",
            "The nerve of this guy to ask me to sleep over with him at his MOTHER'S house.",
            "Yeah, I'm supposed to be on a diet but… fries. Maybe next year.",
            "When I leave you alone, please leave me alone back... Thanks.",
            "I can't argue with someone who can't keep track of their birth certificate.",
            "We're broken up but still sleep with each other every weekend.",
            "I’m channeling my 2005 high school mood right now, so just stay over there and no one gets hurt.",
            "You've never left the USA but call yourself a 'Passport Boy'?.. Make it make sense.",
            "When he breaks up with you, so you buy his cologne and spray it on all your stuff so no one gets suspicious.",
            "I’m not mad, you just need to stop breathing, that is all.",
            "Don't approach me if you don't know your social security number.",
            "I left him but he's trying to hang on to me tighter than Jack hung on to the door.",
            "When he got food for himself but not you even though you said no, so you ignore him and eat half the fries.",
            "You gotta be a bold MF to wake up and smoke weed with NO JOB.",
            "Friends talking about 'leave him alone'... I will leave Y'ALL alone TF.",
            // Upgraded Jokes
            "My gf is on her period. I got the wrong chocolate so I’m looking for a new apartment now.",
            "I could leave but I chose to stay in my hood. YEA OKAY Mr. NI99A.",
            "When you can't let trauma go but still think about the guy at the bar.",
            "When she's mad you can't pound her faster than a jackhammer.",
            "When he gives Buffalo Bill vibes but he's cute so it's okay.",
            "My gf is a cat. Touch me, next min don't touch me.",
            "Yes I still listen to 2000s punk rock don't judge.",
            "I’d say I'll go out tonight but I'd rather let a lion feast on my ballsack.",
            "My therapist said I need to let go… so I grabbed her arm tighter.",
            "Can you just stop existing in my bubble? Thanks.",
            "When you broke up a year ago but you're jealous of his new Facebook relationship.",
            "You say I need a therapist. I say YA MAMA.",
            "I just miss MySpace when life was simpler.",
            "I'd be happier right now if I were the melting witch from the Wizard of Oz.",
            "She broke up with me and moved so I sold my house, changed my identity and moved next door.",
            "I'm kind of in an Edgar Allan Poe mood today so maybe you should run.",
            "When you pull out that pirated 2002 MIX CD to feel your real feelings.",
            "My friend said I look mad. Nah, I'm just a parent.",
            "When your dog dies and you decide to get it stuffed so you can keep them forever.",
            "I want Tacos not roses.",
            "When your breakup is harder than watching the last episode of Game of Thrones.",
            "I'm about to be angrier than my cat in water.",
            "He broke up with me so I decided to get a custom pillow with his face.",
            "I hate weddings. Too many gross people in love and sht.",
            "Hey mom, what's in this box? Oh just your 976 pictures you drew in kindergarten.",
            "Go be happy over there please.",
            "When you miss grandma enough that you get her ashes mixed in with your tattoo ink.",
            "I love you, couch. You understand me.",
            "She broke up with me so I listen to the 'OUR SONGS' playlist on Spotify every night to fall asleep.",
            "Excuse me……I thought you put out.",
            "When your girl breaks up with you but Starbucks is still a part of your morning routine so you still show up.",
            "Yes, I still have my 8th-grade basketball trophies. I was HIM back in the day.",
            "Yes, he has a girlfriend. Yes, we are getting married.",
            "Spoke to my ex, we're still going to keep the same name for our first kid we plan to have.",
            "RED FLAG, RED FLAG, RED FLAG… too bad I'm color blind.",
            "You're an a*shole but I like your face so I guess I'll stick around.",
            "Hey! I am bored. Can you play with my feelings once again.",
            "Only in my head am I safe from the as*holes."
        ]

,
        "LeoButton": [
            "Buying SECTIONS in the club when they on SECTION 8 is crazy",
            "Spotlight? Just follow the crowd's applause; I'm the center of attention.",
            "Drama? Life is my stage, and I'm the star of every scene.",
            "Generosity? I give, and people can't help but love me for it.",
            "Confidence? I'm not just self-assured; I'm practically radiating it.",
            "Roar? It's not just a sound; it's my majestic presence announcing itself.",
            "They ask me why I talk to myself, I tell them because sometimes I need to speak with a professional.",
            "I thought being in a relationship with a liar was bad, until I met a b*tch who only told the truth.",
            "When someone doesn't answer my call within the day, I don’t answer their call for a year.",
            "Thinking about exercise should sooo count. It's a brain exercise.",
            "“So..am I the only girl you’re talking to”..ME: yeh, everyone is asleep already.",
            "I'm a strong independent woman but you need to buy me flowers and attend to my emotional breakdowns.",
            "I don't care if people like me as long as they keep pretending that's all that matters.",
            "I might be broke but this face card NEVER declines.",
            "*police takes my mugshot* my insecure a*s: let me see.",
            "I don't call anyone my ex, I call them the deceased. How could they live without me.",
            "Not even gonna front, I really do think I’m all that and a bag of Fritos, HOTT Fritos.",
            "Staring in the car window dramatically singing to Adele then realizing you took the tint off.",
            "A job job is not cool, they have an app for that now.",
            "Our first argument you better be outside my house with a boombox and roses.",
            "Me: Runs for 2 mins. My heart: If you don't stop, I will.",
            "Of course I wasn't taking you seriously, you were supposed to take me seriously though.",
            "If you see me on multiple dates do a b*tch a favor and let me know who looks better on me.",
            "“Haven’t heard from you in 59 minutes, have a nice life.”",
            "Forget exercising, filters are way more effective method of toning.",
            "Of course they didn’t invite me to the party, I’d take all the shine.",
            "Watch as I dramatically swipe everything off the table to make room for a giant map to explain the plan.",
            "I love giving my man hell and he doesn’t leave me, you love it here huh babe?",
            "I’ll walk into a whole event and only speak to people I like.",
            "Reservations are so embarrassing like 'hi, I'm here for my spaghetti appointment.'",
            "I'm single because people don't know how to swipe right literally.",
            "If you don’t get my name tattooed across your forehead then I cannot take you seriously.",
            "My life feels like an opera. Lots of high-pitched screaming and I've no idea what's going on.",
            "Him: that s*x was so good bae. Me: yes, I'm aware bro.",
            "Me…share a man?? Is it crack you smoke?",
            "Is that a chicken wing? Ew low vibrational food.",
            "There's no moving on from me, it's either ME or GOD.",
            "I hate a man who knows his worth..wtf you mean I can’t cheat on you.",
            "Here's to My b*tches Who Use Tea Spoons for Everything because Big Spoons Give Them Bad Vibes.",
            "I would have lots of friends if they didn't come with so many side effects.",
            "Buys section/bottles in a club… 'Please stay away from my property.'",
            "Yes okay I will get over it, but I have to be dramatic first.",
            // Upgraded Jokes
            "The best piece of equipment in the gym are the mirrors for selfies",
            "When she has more selfies than 1s from the strip club.",
            "If the corner of my fitted sheet pops up one more time, I will die.",
            "Men shouldn't get a say in abortion. Child support Reps need their jobs too",
            "I need more mirrors so I can see myself even when I'm sleeping",
            "I like people who aren't fazed when I'm dramatic, like just let me be, I'll be done in like 10 mins.",
            "I got more people on my blocked list than a pro ball player",
            "I know you said it was going to snow but the public needs to see my Gucci slides.",
            "Oh, okay 'cause I thought the dude that screams at his game called ME dramatic",
            "Marriage ain't for everybody. Just those who can afford a divorce attorney",
            "I refuse to drive a Ford. Can’t be seen as blue collar.",
            "My mom said 'if your friends jump off a bridge, would you?' Mom, I was the one with the idea.",
            "How cool is it that poor people continue to work instead of learning to invest",
            "When she won’t go on a hike with you because there's no way she can be seen in hiking boots.",
            "Someone knocked on my door. I cried, called mom, hid under the bed, smoked a cig then opened the door... it was the mailman",
            "Americans are way too cocky to give up their guns. Plus bullets don't give off the same effect when you throw them",
            "No, I’m getting a surrogate. I’m NOT getting stretch marks.",
            "Two-week lockdown my a*s. I now have a master's degree in zoom meetings & putting tape over my webcam.",
            "Some people are perfect; others are even ugly with a filter",
            "I need a man who works out of the home because I can’t lift more than 10 lbs or I'll break a nail.",
            "If your patient doesn’t want to get out of bed, order them a stripper. Works every time.",
            "A lot has changed over the years; fat is now spelled B-B-W",
            "Feminism is a man buying me all my sh*t so I can be happy.",
            "It's 2023, so I have OnlyFans, FeetFinder, and Twitch. I'm hustling and you can't judge me.",
            "Congress & their egos... shouldn't real gangsters & criminals be more upset about gun control?",
            "I’m more vegan than PETA",
            "Went to confession for cheating on my wife. Turns out she's been banging the priest, so we're EVEN!",
            "People aren't really vain; they just have filter options now",
            "I stay away from the water so Ursula doesn't try to steal my looks.",
            "When you think it's the FBI knocking on the door but it's just your mom bringing you soup.",
            "I'm waiting for the day when Wal-Mart starts selling great value packs of Facebook likes",
            "When he has a V8 muscle car to avoid talking about his daddy issues.",
            "I’m not saying I want to fight, but these flip flops might say otherwise",
            "I don't care about gas prices... as long as my Uber driver doesn't run out of gas",
            "Don't use the Lord's name in vain... Me: 'GOD DAMN, BISH, I look good today'",
            "When I get in my car, I scream as loud as I can. For your protection, not mine.",
            "Abortion is not an issue most of us care about because we made the cut, duh",
            "Yes, she said I'm so vain but like, she wrote an entire song about me so I'll take it.",
            "Of course, I'm dramatic. I was a theater kid for all of high school",
            "No one says it's not you, it's me anymore. Instead we say you're the toxic narcissist",
            "I never use any filters as the literal filter is linked at the bottom of the video",
            "You're being very 2007 Britney Spears right now",
            "I don't drive a fancy car, I just pose in front of one occasionally for an IG selfie",
            "When she brings her 10lb makeup bag on a hike and makes you carry it.",
            "I’m about to go 3 am at 7/11 on your a*s.",
            "The audacity to i.d. a caller as scam likely, yet still so politically correct wow",
            "When she has to take a selfie before sex so the world knows she's getting some.",
            "I may not be the queen of a country, but I sure are the queen of drama",
            "Inflation is everywhere; you can't even throw dollars at strippers anymore",
            "I need a man that works hard enough for me to get my nails done, pay my bar tab and doesn’t ask when I’m with another man.",
            "When you date a vegan and she loves avocados more than you.",
            "I leave texts on read because I don't always feel like reading",
            "My face recognition never works. I think it's because I look better than the photo the camera takes",
            "I was breathing wrong so mom threw a shoe at me for my attitude",
            "If I was ugly I'd still wear my mask, it's the closest thing real life has to a filter",
            "I’m an influencer now give me all the free sh*t",
            "I had a card reading today and she said my future looks bright so I'm buying a travel van and becoming a YouTuber.",
            "It doesn't just take two to make a baby, you have to subtract the condom also",
            "Maybe I should continue wearing a mask, most people don't deserve to look at me",
            "Honestly Kelly, I’d rather get hit by a car than go to your 9th baby shower but thanks for the invite.",
            "Who said everyone makes mistakes? What an idiot",
            "I'd love to meet the person who said no one's perfect, then they will stop saying it",
            "When grandma dies so you can finally order the stripper grandpa’s been asking for.",
            "I would marry but they don't allow you to marry yourself just yet.",
            "I would offer beauty tips, but I feel bad they will never look as good as me",
            "Memories of me being awkward in school still haunt my dreams like Freddy Kruger",
            "I only eat kale and caviar because vibes.",
            "My girl curfew is 8:30 pm sharp this summer"
        ],

        "VirgoButton": [
            "Did you see that organized closet? Yep, that's my masterpiece.",
            "Perfectionism? I'm not obsessed; I just want everything flawless.",
            "Routine? My schedule is a work of art, down to the minute.",
            "Detail-oriented? I spot what others miss; it's a gift and a curse.",
            "Analyzing? I can dissect a situation until every angle is explored.",
            "I'd like my coffee with a pinch of sugar, & brown color #D3E554",
            "'Wrong bch' really irritates me. An Organized man like myself would never mix up my h*es",
            "I use to bring my tv remote to school thinking it was my calculator.",
            "I only asked for 12 sprinkles, why is there 15?!",
            "Types of vacations I need: a week to deep clean everything I own, twice.",
            "Hit's curb, scrapes the brand new chrome rims & giggles like it's funny.",
            "I only date guys that have electric cars, I'd be damn if I pump gas.",
            "Types of vacations I need: a week to just sleep, then sleep some more.",
            "WHOPPS! DID I DO THAT?!",
            "Talking about I only eat organic, with all that BUTT u be eating.",
            "Sometimes I'mma just agree with everything u say & let u be wrong.",
            "When u get into a heated argument, realize u're wrong & now u initiate the break up.",
            "I'm a very picky eater, I only eat human food.",
            "Me: If I'm withdrawn but reliable & they'll see the real me. Also Me: God why does everyone think I'm a psychopath.",
            "I got rid of all my white clothes, im sick of looking like I peed my pants.",
            "Girls say I'm too picky and unrealistic when it comes to women, yet u keep taking filter pics that grab my attention.",
            "Types of vacations I need: a week where I don't speak to anyone.",
            "When I face even the slightest obstacle in my life, I call my parents.",
            "Manufacturers are such liars, I weighed a bag of chips and it was way off from the weight on the label.",
            "I think i might be the saddest happy person and the meanest nicest person to ever exist.",
            "Ya'll drive on E, I drive on F.",
            "I swiped left to the end of tinder not one freaking cute girl.",
            "If this sign says \"first of all\" Run away bc they've prepared research, data, charts and will destroy u.",
            "When u flush ur Airpods down the toilet.",
            "When u don't let any little detail slip by.",
            "I'll show up to work on time when u pay me for my time.",
            "My wife is mad at me for breaking the dishes, but it’s her fault for making me clean them.",
            "When someone says 'it's just a minor detail' and u're like 'NO, it's a Knit-picky!'",
            "Nobody: calm down Me: I was calm before u said that now I wanna choke u.",
            "When u break something and fix it enough that the next person who uses it thinks they broke it.",
            "I'm either too direct or don't express my emotions at all... there's no in between.",
            "Them: u're so quiet in person. Me: My spirit doesn't like u.",
            "When the doctor gave u 3 weeks to live so u rob a bank and the judge gives u 20.",
            "Do I want space or attention? One will never know.",
            "If u think i'm mean, u should hear the voice in my head.",
            "GOT SO HIGH I ASKED GOD TO UNHIGH ME.",
            // Upgraded Jokes
            "When u're trying to decide if u're too knit-picky for ur own good.",
            "Whenever I stretch my arms some glasses break.",
            "I only eat organic, non-gmo, locally grown kale, not that processed sh*t.",
            "I love acting clueless when I know exactly what's happening.",
            "My Spanish teacher asked me to turn in my essay, but I’d never betray my friend like that.",
            "I only sleep on silk sheets with a thread count of 5 billion and 2.",
            "If I just get 1M followers I can buy an 18 pack of eggs.",
            "My colleague told me he needs a break, so I told him there’s an auto shop down the street.",
            "When the barista has to use three stickers on the cup to fit my drink order.",
            "Me sending my friends encouraging messages even though my life is a hot mess too.",
            "Puts in 10 pairs of socks in wash, somehow leaves with only 2 left.",
            "I only shop at Target bc… If you shop at Walmart we cannot date.",
            "I'm not a control freak, I just like things done my way.",
            "Babe, I'm not nit-picking u I'm just saying u didn't put the 19 ½ pillows on the bed in the right order.",
            "I'll wait 10.3 business days to respond to ur “emotional breakdown” u messaged me about.",
            "When they have 30 different color towels in stock but u NEED the light chartreuse for the bathroom.",
            "My horoscope said bad sh*t was going down today but so did my boss. I’m staying home just in case.",
            "He's cute but there's one long beard hair and ion like it.",
            "My OCD is so bad my house tries to clean me.",
            "I want help cleaning but the towels, blankets and fancy soaps HAVE to be in the correct color pattern.",
            "I only have to take 28.3 meds a day to hold this conversation.",
            "I like things tidy. No dear, u like the house to look like a Tesla showroom. There's a difference.",
            "My therapist says I need a 5 year plan. I’m trying to figure out what to even have for dinner tonight.",
            "I’m not mad, I'm angry, get it right.",
            "Yes i'll respond to ur text but only after I have 2 shots and a xanax.",
            "Yeah I need a burger with no pickle, no tomato, no cheese, no bun.",
            "I finally got her to pick food. It may be for 7 different things from 7 different places, but I'd say we're making progress.",
            "If the temperature in my house drops below 72 someone's gonna die.",
            "When u’re a photographer, so u have to take 50 of the same shot just to get the right lighting.",
            "I rewrote my assignment 4 different times only to get a 99 on the paper.",
            "My baby hairs aren't participating today so tonight's canceled.",
            "She won't eat bacon bc it comes from a pig but eats pancetta bc charcuterie boards are cute.",
            "I don't need a virgin I just don't need to deal with 6 baby daddies.",
            "My throw pillows are taupe, not tan idiot.",
            "When she hates cats but wants a pet tiger.",
            "I'll only use 2.5 squares when going to the bathroom. 3 is too much in this economy!",
            "When mom only let's u take a 3 minute shower bc u don't pay them bills.",
            "I have salt packets in my car bc none of them b*tches can ever get my fries right.",
            "When u're doing dishes but get a hair on ur hand so u have an aneurysm."
        ]
,
        "LibraButton": [
            "Decision-making? Let's consult a committee before I choose.",
            "Balance? It's not just a yoga pose; it's my life philosophy.",
            "Harmony? I'm like a mediator superhero, always restoring peace.",
            "Social gatherings? I orchestrate events like a seasoned conductor.",
            "Flirting? I'm not just charming; I've mastered the art of attraction.",
            "BLCKEDDD UNBLOCKEDD CUSSED OUT BLOCKED AGAIN",
            "Life be simpler when u nonchalant, soon as u start chalanting sht go left",
            "I be praying then randomly think about what ima eat for breakfast tomorrow",
            "I hate when girls say I'm Indecisive, btch I ghosted u, decision made",
            "If the party is full of people with no license or bank accounts do NOT invite me!",
            "Them: Hey. My name is Jonny ME .01 secs later: dam, what was his name again",
            "Being indecisive ain't so bad, I dispute every purchase & it pays off",
            "u got .0102012 secs before I cut u off, come CORRECT!",
            "I study for 5 min then find myself on youtube watching a series about Street Food in Tijuana",
            "Sucks that I can't stick with one solid excuse to call in to work",
            "They out here eating low vibrational food, take me home please",
            "I was going to make a joke about procrastination, but I kept putting it off",
            "I asked my girlfriend what she wanted for dinner. I’m 35 now and still waiting.",
            "If I see a dude with black air forces walk in, I'm leaving IMMEDIATELY!",
            "Me: I'm going to focus on this task... My Brain: get somebody else to do it!",
            "Do I vote for the person who actually knows what they're doing or one who won't get me canceled?",
            "U not about to fight my girlfriend looking like the girl version of mike tyson",
            "After my 3rd 'That's crazy' please stop talking",
            "Dating me is like knowing if the ice cream machine is working at McDonald's so choose wisely.",
            "When someone wants to argue, just smile and nod, then slide in their man's DM",
            "Ya'll ever been so drunk u forget to have s*x",
            "I go outside I regret it, I stay in and wish I was out, I need HELP",
            "When in doubt, smoke an L",
            "Once I hit 30+ I be having to calculate my age counting up from my birth year",
            "Do I sign up for FeetFinder or work at Walmart?",
            "When it comes to conflict, I'm an expert at avoidance",
            "Looses custody of kids, goes out on Saturday night like nothing happened",
            "Do I make a paycheck today or do I give my paycheck to Netflix",
            "I have zero friends with short hair. Don't need any of that Karen sh*t going on.",
            "I heard playing jigsaw puzzles helps with concentration, so I binged all the Saw movies",
            "To have or not to have kids. More like to pee or never pee alone again!",
            "I stay home bc if the world comes to an end I need to know where my towel is.",
            "Tryna learn more skills, but YouTube tutorials always lead to binge-watching shows I've already seen",
            "Should I buy these eggs or pay for gas?",
            "I stay off of Tinder bc creepers",
            "I've mastered looking people in their face and not listening to anything they said",
            // Upgraded Jokes
            "I only love u but I want an open relationship.",
            "Wish there was a Karen button for social media instead of everyone fighting in the comments.",
            "I once spent 5 hours playing Sudoku bc I was trying to impress my Asian girlfriend",
            "I want to make lots of money but my bed doesn’t yell at me like my boss.",
            "I take Xanax to go to Walmart so I don't punch someone but still get good prices",
            "I don't always procrastinate, but when I do, I’ll do it later.",
            "Do I fix the Ford again or pay off my house? decisions decisions.",
            "If weed were federally legal the Karen count would drop",
            "When finding a new job is easier than finding out what she wants to eat for dinner.",
            "Family function tonight so I'm taking a gummy now so when they judge me, I don't swing",
            "I refuse to go to therapy because I'm my biggest critic and won't be nice.",
            "Driving in 5 o'clock traffic is like WW3 so I work from home now.",
            "When u refuse to have another relationship because deciding food for someone else is too much.",
            "I don't want to have kids, my mom already judges me enough",
            "When u hide in the bathroom to eat a piece of candy so ur kids don't demand the entire bag.",
            "I want a virgin girlfriend. Can't be dealing with jealous baby daddies.",
            "I play video games because when sh*t goes down I can just start over.",
            "My students aren't the bad part, it's the parents who are assh*les.",
            "When the felons tell u the truth more than the priest does, so u don't go to church anymore.",
            "I can't be a social media influencer, wayyy TOO sensitive",
            "When u work in the psych unit so u can scream without being committed urself.",
            "Im an influencer because I can handle the comments better than another zoom call.",
            "I always wear headphones so I don't have to hear the stupidity in public.",
            "Just need a sugar daddy because my boss is an as*hole.",
            "I eat the same thing every day so I don't fight with myself for 45 mins tryna decide",
            "Clubbing can be ur happiness but mine is a weighted blanket and nap."
        ]
,
        "ScorpioButton": [
            "Secrets? They're safe with me. I'm like a vault of mysteries.",
            "Intense? My emotions run deep, and I don't hold back.",
            "Detective skills? I can uncover the truth even in the shadows.",
            "Passion? It's not just a word; it's the fire that fuels my every move.",
            "Transformation? I embrace change like a phoenix rising from ashes.",
            "I just made this man confess some sh*t I made up in my head",
            "I'm soo scared to get my feeling hurt again cause I promise ima be on the news",
            "If u cheat on me while I'm being a step mom. I'm leaving ur kid at the park",
            "This would have never happen if u never caught me cheating",
            "Would u like a pic? F*ck is u staring at?",
            "When u get ur revenge, don't forget to take a selfie!",
            "When he says he doesn’t want a relationship but gets mad if another man walks within 10 ft of u",
            "UMMM CAN I HELP u?!",
            "Boss won't cover my shift so I'm not covering his affair.",
            "I need to control ur life so this relationship can work",
            "IF BLACK AIR FORCES WERE A PERSON",
            "Revenge is a dish served with a side of satisfaction.",
            "I'm never leaving a club early again in my life, I'll even help them cash up.",
            "u ARE NOT HIM!! MORE LIKE HER LMFAOO",
            "It still bothers me that I didn’t cheat on my ex",
            "I make sure the s*x is trash so I can make sure u like my personality like u said u did",
            "I NEED A RUFF NECK..BARK AT ME DURING S*X",
            "He cheated so I texted every girl he knows and told them they need to get tested.",
            "For someone who keeps saying 'it is what it is' I honestly have no idea what it actually is",
            "Even look at my dog wrong and I'll go John Wick on u’re a*s",
            "She slept with my best friend so I slept with her mom and now I'm really her daddy.",
            "Not to be dramatic but the sun setting at 5:00 pm every day has ruined my life",
            "Sometimes I get road rage walking behind people at the grocery store.",
            "I be wanting to tell people happy bday but I never got one so fk it",
            "I spend money like it'll solve my problems",
            "If we break up, I do not wish u well. I hope u get chased by hyenas",
            "My girl left me so I told her dad I'm the better daddy.",
            "Why does asking for money back that ur owed feel like a crime",
            "Being around me is fun n games until my attitude is activated",
            "My boyfriend cheated so I moved in next to him so he can hear what I meant by go faster.",
            "Don’t hit me up after ur little relationship didn’t work out",
            "I LOVE u, But F*Ck u",
            "If he cheating, cheat back. Support ur man in everything he does.",
            "Don't worry babe, yeah we use to FK but we just besties now",
            "I'll commit crimes before I commit to a relationship",
            "The bishop excommunicated me for cheating on my husband so I slept with his wife.",
            // Upgraded Jokes
            "People without glasses really just out here seeing life for free.",
            "I don't feel bad for my man when I go crazy anymore, this the life he chose",
            "Don't break his Xbox, just delete all his saved info & watch him cry himself to sleep.",
            "People who can read my sarcasm without me feeling urge to say joking are top tier",
            "I hate going back and forth, I be ready to SWING",
            "When he cheated on u so u finally tell him how many times u had to fake that orgasm.",
            "Apple automatically copying the verification code from messages is bad as*",
            "You can’t spell ‘pacifist’ without ‘fist’",
            "He finished the last taco so u finish the rest of the weed",
            "So apparently I cheated on her in her dream last night & I have to confess in real life",
            "I’m very aggressive when I’m drunk, but that’s just the Henny talking",
            "Baby daddy didn't take the kids again so I get full custody so and his child support raises hehe",
            "You're breathing wrong again so we're breaking up.",
            "Threw my coffee at the waiter bc he spelt my name wrong,  i mugged him LMFAO",
            "Eve only ate the apple bc Adam was annoying her.",
            "I listened to 90's R&B today. They said I deserve better and it's ur fault so bye!",
            "I’m a wise man but these hands are senseless",
            "When he cheats on u so u buy a yellow jumpsuit and a katakana.",
            "I ordered a steak for dinner & she got the salad. I didn’t offer her my steak so apparently I'm not a man",
            "I’m only pro-abortion when I take public transportation",
            "He didn't change the baby so I set a lego next to the bed for when he wakes up",
            "She's looking at me like I did the wrong thing again. It's only 7 am so pray for me",
            "If u annoy me I will turn ur life into a horror film",
            "Told my therapist I didn't know if I was feeling vengeful or just a little spicy today.",
            "She said it was her or the game. I just upgraded my console.",
            "If I don’t have my coffee in the morning, someone’s getting put on a shirt.",
            "Boss won't cover my shift so I'm not covering his affair.",
            "My girlfriend said it's her or the dog but the dog knows what it wants for dinner so BYE!",
            "My neighbor stole my hay cart. That’s the last straw no pun intended",
            "God said vengeance was his…. Too bad for u, I don't believe in god",
            "When she asks if u want tacos, the answer is yes bc it’s that or ur life buddy.",
            "Careful what u say to me, my grandpa fought in the war, and his rifle still works.",
            "My boyfriend said I'm not attractive anymore but that's not what his bro said last night",
            "Job's talking about mental health being a priority so how TF I got fired for going to a doctor's appt",
            "My future me is probably laughing at me right now, jokes on him I’ll f*cking ruin his life",
            "Just in case he cheats, make sure u know his bank account info better than he does.",
            "I won't tell u what I want to eat but if u don't get it right they'll be hell to pay",
            "The relationship finally becomes meaningful n fun once the police are called",
            "He broke up with me so I did one last nice thing for him and filled up his tank… with diesel.",
            "I need to fight with him today so he has to tell me I'm pretty.",
            "My boss said I couldn't have vacation time so I'm on OF now & mailed her hubby some nudes",
            "YES, communication is key but NO, don't talk to me",
            "When ur girl wants u to take her out to eat but she was being childish earlier & wouldnt let u fk so you play broke",
            "I want you to be in control but listen to everything I say",
            "I can't wait to retire so I can get up at 6 AM and go drive around really slow & make everybody late for work"
        ],
        
        "SagittariusButton": [
            "Wanderlust? You bet! My passport is always ready for an adventure.",
            "Philosophy? I ponder life's big questions while others are still waking up.",
            "Optimism? I'm not just hopeful; I see the silver lining everywhere.",
            "Adventure? My bucket list is as long as my tales of epic journeys.",
            "Freedom? I can't be caged; I'm the free spirit of the zodiac.",
            "I be on vaca waking everybody up before sunrise, stay home if yo a*s wanna sleep",
            "Dating me is not for the weak, I make up random stories in my head and bring up issues from the past",
            "I beep the horn loud af outside my sneaky link crib for excitement",
            "I make weird noises & yell out random movie quotes",
            "I hate it when I'm singing a song & the artist gets the words wrong.",
            "My wedding cake gonna be an edible & I'm not warning anybody",
            "Drunk by 2 am, work by 7 am, a responsible drunky",
            "When the pole dancer turns around and she’s pregnant LMAO",
            "I AIN'T GET SLEEP CAUSE OF Y'ALL, Y'ALL AIN'T GETTING SLEEP BC OF ME!!!",
            "I nap for your protection, not mine. I can go ALL DAY!!",
            "Got to stay off indeed. I got an interview at NASA tomorrow",
            "When your joke is bomb & you gotta wait for the squad to settle down",
            "If you're still waking up after 9 am, YOU ARE A MANCHILD",
            "This morning I was in love, tonight I'm for the streets",
            "When you purposely don't stop the microwave before it reaches 0:00",
            "I noticed you're taking a nap in the middle of the day without an alarm... I too like to live dangerously",
            "So my therapist retired today. I still need help but hey at least he's happy.",
            "THIS NI99A WISPER SOUNDS LIKE A GROWL",
            "I love my ambitious hubby but the ER bill is getting a little too high.",
            "Today I am He/Him. Tomorrow She/Her. Friday I'm both",
            "Some of y'all need a mute button",
            "We all have that one friend that is up at 4 AM trying to take over the world.",
            "When the priest asks to be in the puff puff pass circle",
            "I sound like a dolphin when I sneeze",
            "I will ruin your day at 6 am sharp IDC!",
            "All I asked for was one threesome. now the 3 of us have a wedding scheduled in Vegas",
            "My friends don't like to bring me nowhere, they say I'm too LOUD",
            "That friend that calls before 8 AM wondering what you're up to",
            "When the weather is more predictable than her mood.",
            "I TALK IN ALL CAPS!!!",
            "The FDA says 400 mg of caffeine a day is where I should stop but the FDA doesn't own me.",
            "When she takes anal better than the guys in your unit did.",
            "I can sneak a midnight snack for sh*t, I always end up trippin on my way to the fridge",
            "When they're on Adderall but you're on Valium",
            "I went to prison one time. Now I have a soap saver and an infected mom tattoo.",
            "My upstairs neighbors stomp to get me to stop my music, but I just dance to the beat.",
            // Upgraded Jokes
            "When they like teen pop music but you're more into Beethoven.",
            "When you share a blunt in the confession booth",
            "People ask me why I’m so loud... umm I'm BLACK LMFAO",
            "Even the scream painting has more energy than I do in the morning.",
            "My wife's mood is more unpredictable than this economy",
            "I like to drink water so hard the plastic bottle starts shrinking",
            "I'm friends with ghosts because humans are just too much.",
            "My stepdad really, really... really likes my sister.",
            "Never enter a shouting contest with me",
            "Your girlfriend acts normal, my girlfriend acts like a Labrador.",
            "People always blame God for their troubles, but I just blame my mental illnesses.",
            "My horny a*s, room be sounding like a barbershop at 12 am",
            "When you need 9 shots of espresso in your coffee to function around other people",
            "I don’t always go to the zoo, but when I do, I always attempt to talk to the monkeys",
            "Wednesday Addams is my spirit animal.",
            "She said my aura is off, now all of a sudden she's burning sh*t.",
            "Don't make plans with me for after 8 pm or I'm not going",
            "Happy people make me uncomfortable. We're all gonna die anyways.",
            "When you try to caffeinate yourself and just end up increasing your heart rate"
        ],
        
        "CapricornButton": [
            "Goal-setting? I don't just climb; I conquer mountains.",
            "Ambition? My dreams have a GPS, and I'm heading straight there.",
            "Workaholic? It's not just a job; it's my legacy in the making.",
            "Responsibility? I'm the reliable one people turn to in any crisis.",
            "Discipline? I'm not just organized; I'm a master of self-control.",
            "I smell so good you're gonna moan a little when you hug me.",
            "I'm sorry but 3 or more kids in your 20s is crazy.",
            "I'll share my location with my boyfriend & still cheat, I don't give a f**k.",
            "I'm not saying you're a bad person, you're just not as good as me.",
            "These men in my DM's be BROKEEE.",
            "You THOUGHT I WAS FEELING you?! you LOOK LIKE A MUTT.",
            "Oh, you're vegan? I didn't ask, but thanks!",
            "It feels so good to be 0 weeks pregnant.",
            "Boyfriend cheated, so I got pregnant by his stepdad.",
            "Every time I taste my cooking, it just assures me I'm wifey material.",
            "Going out with heartbroken people is LIT. These mfs drink to DIE.",
            "Go disappoint your Momma, NOT ME.",
            "I'M REALLY HIM!! I'M THAT GUY.",
            "She done sent me 5 attachments. Each one uglier than the last.",
            "Dudes be asking where the b*tches at but never look within themselves.",
            "I'm getting a little jealous vibe from you! Am I right?",
            "Never would I date someone with an STD, been there, done that.",
            "Fat people always got something to say... now if I say something back, then I'm wrong.",
            "I already have my complaint forms pre-signed.",
            "I feel sorry for married people, single & miserable is so much better.",
            "If we don't work out, that's cool, but don't ruin my chances with your friend.",
            "Linda got a tattoo. Guess no heaven for her.",
            "If you ate a man's bootie, you should try Fear Factor.",
            "I might not cheat but I know who's next for sure.",
            "When the vegans yell at you for breathing their clean air.",
            "Yes, I judge people with multiple baby daddies... FIGHT ME!",
            "I'm taken when he's around, single when you're around.",
            "I'm better than you. I'm a child of GOD!",
            "You can't cook? We can't date. PERIODT!!",
            "THEM: You single?? ME: Sometimes, why?",
            "When your aunt says you need to do better but she's on her 5th marriage.",
            "Love it when I see my ex dating Gargoyles LMFAO.",
            "You look like a 'Monday' morning LMFAO.",
            "Gross, you smoke weed? - pops another percocet.",
            "When you hate people more than the virus.",
            "THIS SIGN IS FOR THE STREETS!!",
            // Upgraded Jokes
           "I'm a Feminist. Why? ...because I'm better than you.",
           "Sometimes I feel useless, but then I remember I breathe out carbon dioxide for plants.",
           "You might not be my only one, but you sure are my favorite LMFAO.",
           "No, I'm not self-righteous; I'm just saying you need to be more like me.",
           "Oh, the Marine is coming? I'll set out the crayons for dessert.",
           "Sorry, I was weird last night. It was to move the plot forward.",
           "Mom said aunt Kelly is making the turkey for Thanksgiving. KFC HERE I COME!",
           "Talking about your feelings is SO important. I won't do it, but you guys definitely should.",
           "She says she has a job but gets pedicures every week and has a better camera setup than Fox.",
           "I don't ask men if they ate because I truly don't give AF.",
           "Baby daddies be like 'New day new me.' More like new woman and more BACK child support.",
           "YES, I live with my wife... NO, I don't come home at night.",
           "If you don't know where your blinkers are, then I don't know where my brakes are.",
           "I'm not dating to marry. I'm dating to experience a painful breakup that kickstarts my weight loss.",
           "If my girlfriend runs out of gas again I’m getting her an electric scooter.",
           "If you cannot afford an iPhone then WE cannot DATE!",
           "Oh, you drive a Ford? It's okay, the next repair shop is only a mile away.",
           "Shout to my baby daddy for babysitting while I take these backshots tonight.",
           "If you can't order your coffee in under 10 seconds, you're doing too much.",
           "Yes 'n*t in me please'… proceeds to abort the baby.",
           "I appreciate ugly people, they make me feel so grateful.",
           "News flash I don't fu*king care.",
           "My kid looks at me harsher than Judge Judy if I don't give him my coffee.",
           "No I'm not judging you... yet."
           ],
        "AquariusButton": [
            "Rules? I'd rather invent new ones and see where they take us.",
            "Innovation? I'm not just creative; I'm a visionary thinker.",
            "Humanitarian? I can't help but fight for a better world.",
            "Rebellion? It's not just a phase; it's my lifelong outlook.",
            "Individuality? I march to my own beat, and the parade follows.",
            "When you tell her 'NOT TODAY' and she instantly starts imagining life without you.",
            "I'll never tell him this, but sometimes my man be making a lot of sense.",
            "I ghost people because I fall in love quickly.",
            "I say 'I love you' on the first date.",
            "When you try too hard to fake a smile.",
            "I imagine fake scenarios & just end up hurting myself.",
            "Thanks to buy now, pay later I now basically have another car payment.",
            "Please give me space but also attention.",
            "I hate when people raise their voice; then I have to cry.",
            "20 minutes after ordering a package online… ME: Where ya'll at with my package!!!",
            "Me in the work bathroom giving myself a pep talk about not to quit out of anger.",
            "When I say 'be safe,' I mean that from the bottom of my heart.",
            "When someone is getting attached too early… Hmm yes baby I like you.",
            "'If you're waiting for me to message you first, we will never talk.'",
            "I will literally cry if I find out you ate already without me.",
            "I stop myself from being rude so many times a day and NO ONE appreciates it.",
            "I only fight with someone when I know I'm right. I be fighting a lot LMFAO.",
            "When he says 'I'm so glad you're not one of those crazy girls' LMAO.",
            "WTF is a 'talking stage'? Like, I want your soul NOW.",
            "I said No but I really meant ABSOLUTELY NOT!!",
            "My biggest toxic trait is I know how to love but I don't know how to believe I'm loved.",
            "I'll ask once, more than that feels like begging.",
            "When you agreed to go out and the time to go out is getting closer.",
            "Now... let me find the perfect song to cry to.",
            "TF is 'taking things slow'? Put me in your WILL.",
            "Sleeps after a long day of ignoring their feelings and pretending to be heartless.",
            "He getting me drunk to get some but jokes on him I'm about to start crying.",
            "I hate baby steps, let's get Married.",
            "That was a worse idea than when I got back with my third baby daddy.",
            "Nothing hurts more than when you send a meme to someone and they already seen it.",
            "When you finish a good book & need everyone you know to also read it asap so you can discuss.",
            "Somebody: you can't touch cactus, it'll hurt too much. Me: Hold my feelings.",
            "When you realize your eraser dies slowly because of your mistakes.",
            "Ladies, if a man says he will fix it, he will. There is no need to remind him every 6 months about it.",
            "Me, getting ready to make the same bad choice again!",
            "Every time I let someone in they disappoint me.",
            // Upgraded Jokes
            "When your boo is busy but you want their attention but you lowkey understand so you just have to wait.",
            "Me trying to convince myself to stop being stubborn, stuck up, rude, mean, moody, & a cry baby.",
            "Girls need a good photographer more than a boyfriend.",
            "This sign falls in love in 24 hours.",
            "I don't know why but my brain can Speak Better English than my mouth can.",
            "If crying was a superpower, I'd have saved the world by now.",
            "One of the worst mistakes you can make is to quit on the person who fought for you. Never leave loyalty.",
            "Slapping your best friend unnecessarily can reduce your stress by 90%.",
            "You never know when your dear becomes your tears.",
            "Nothing pisses me off more than when someone doesn't fking text me back.",
            "Obviously short girls are stubborn bro. Look at her, she even refused to grow.",
            "Learn to be ALONE because Everyone leaves!",
            "I'm sorry I annoyed you with my desire to not die.",
            "The moment you realize you've been arguing for an hour but you were wrong AND LATE.",
            "Learn to say no without explaining yourself.",
            "When a page takes more than 2 seconds to load... ME: Tech support? I have a virus.",
            "I do a lot but admitting I'm cold to my mom who told me to bring a jacket isn't one of them.",
            "I hate that I'm a stress crier and a happy crier and an angry crier. Look, I cry for everything ok.",
            "WTF is a 'talking stage'? Like, want your soul NOW.",
            "Nobody's more stubborn than an Android person that won't switch to iPhone.",
            "If you make ugly faces while crying, you didn't really have a breakdown.",
            "I don't like to waste time.. Are we gonna hunch or not?!",
            "Can't find my socks so I disassembled my whole a dryer.",
            "She's got a specific dck in mind bruh, Leave her be.",
            "Me in a 5 min meeting: 'this could've been an email'.",
            "I know what I want to eat but if I actually tell him, the game will end.",
            "Big Heart, wrong generation.",
            "I hate it when my game on my phone makes me watch 30 ads to level up just once.",
            "When he says you're being a brat so you make it your whole personality :D.",
            "I take showers so I can feel like I can still cry.",
            "The sexual tension between me & the leave meeting zoom button >>.",
            "When your therapist says you're better now so you adopt an irrational fear so you don't have to deal with the real world.",
            "My hobbies are crying and self sabotage.",
            "When you want to be happy but people know you as the stubborn btch so you wear that crown.",
            "I am a professional cryer. Got my master's just last week.",
            "I know I can make money but I'm too stubborn to put in the effort needed.",
            "Just want to cuddle and be sad no questions asked.",
            "When you've died in this level 34 times but you know you can win.",
            "When the McRib treats you better than your last girlfriend did.",
            "Going to work on 4 hours of sleep because you tried to salvage some sense of freedom by staying up late.",
            "I miss him when he’s gone but miss him more when he's here but not present.",
            "I want to have fun but I'm an introverted hobbit so please leave.",
            "Adulting is too hard. Going to get a job sleeping.",
            "PlEaSe TaR BeNdEr JuSt OnE mOrE sHoT?!",
            "If your therapist starts making sense, quit! Self sabotage is funner.",
            "Yes Netflix, I'm still watching so stop judging me (snoring 2 minutes later).",
            "I frequently go to escape rooms, because after a while someone comes to see if I’m okay.",
            "I know I should eat better but.. bacon, so maybe next year.",
            "I can’t see eye to eye with people because they all look down on me.",
            "I asked her what she wanted to eat but apparently I'm the worst because I should already know.",
            "I’m so sad I’ll eat comfort food until I’m uncomfortably fat.",
            "When you know you're wrong but keep fighting anyways.",
            "If I were any more emotional, I'd be an actual emoji.",
            "She's stubborn as hell but gives good head.",
            "When you are really really sad, trying not to cry and someone asks 'are you OK?' so you breakdown.",
            "When you've been arguing all day but now you need some D so you make him a sammich.",
            "I’m not fat, I’m just horizontally challenged.",
            "Yes, I seen it. smelt it, touched it but I still don't believe it.",
            "If you eat and sleep good, exercise and always drink water, you will die anyway.",
            "When a toxic relationship sounds funner than your current 9-5.",
            "Collecting red flags is my favorite hobby."
            ]
,
        "PiscesButton": [
            "Dreams? I dive into them and swim in my imagination.",
            "Intuition? I sense things others miss, like a psychic without the crystal ball.",
            "Empathy? I feel for everyone, even fictional characters on TV.",
            "Creativity? I'm not just artistic; my ideas come from cosmic inspiration.",
            "Daydreaming? It's not a distraction; it's where my magic happens.",
            "How u accuse of me cheating, whole time u had more side pieces than KFC",
            "I date broke boys so I can control them..act right or gimmie that $10 back!!!",
            "I don't actually exist so if u ever met me it was a prank",
            "Some of ya'll should require to take IQ tests before birthing a human",
            "Goes to strip club with tax return check: 'u know I can take u away from all of this right?'",
            "When u try to start a fire with wet wood",
            "The fact that I've NEVER cheated is pretty dam impressive",
            "The weed man has a family to support too, that's why I buy",
            "My sexual intercourse body count resets every year",
            "I can't belive u canceled plans that I never intended on showing up to",
            "I love to hear people's problems, it's the only reason I read dating profiles",
            "Saying bye Felicia is way more considerate than ghosting dont u think?!",
            "I got covid, food was tateless for a week, might as well have gone vegan",
            "Instead of proposing to my girlfriend,  I'm going to introduce her to my divorced friends",
            "Last night I tried fixing my car with duct tape",
            "I hope u know masturbation is sex with demons",
            "I landed me a sugar baby ya'll..All he needs is help with his homework",
            "I don't like people in real life, but I'm going to like everyones post on Facebook to be nice",
            "Next time u bring ur man on the girls trip, he has to sleep with one of us",
            "I took one for the team when I got married. America u're welcome",
            "Damn, did I forget to cry today?",
            "I got $100 for anyone who hasn't flirted with more than one person this year",
            "The hacker has bills to pay too, that's why I use easy-to-guess passwords",
            "I don't procrastinate. I wait until the last minute to do things bc I will be older and n wiser",
            "Obviously the person who created mirrors did it to be spiteful to ugly people",
            "I love to hear people's problems, it's the only reason I volunteer at the crisis hotline",
            "I love u as passionately as my emotion-dulling medications allow",
            "Good men aren't hard to find, u just don't fit the description FIONA!",
            "Sure, u can borrow my car for ur bank robbery, u need to get there safe don't u",
            "My emotions are as unpredictable as the price of gas",
            "If u owe me money the only thing u should be eating around me is ur fingernails",
            "I'm the realationship expert who hasn’t been in a relationship",
            "Ghosting someone for just a few days and returning as if nothing happened",
            "u accused me of being untrustworthy, but the whole time u had more secrets than the CIA",
            "I love the 3 am version of people. Vulnerable. Honest. Real.",
            "I need u to text me every 30 seconds saying that everything is gonna be OK.",
            // Upgraded Jokes
            "Marijuana had to be legalized. How else was the irs gonna get their cut of drug money",
            "Fine, u can borrow my motorcycle for the getaway vehicle, as long as u promise to wear a helmet",
            "I think i might be the saddest happy person n the meanest nicest person to ever exist",
            "I figured it out, fathers day is a chance to make fun of dads",
            "Who is stupid enough to give multiple chances to people who don't deserve it..ME",
            "When u're kinda dark and twisted but still able to brighten up everyone's day",
            "Salmon taste gross..ya'll eat that for attention",
            "Yes, I've seen their red flags but that’s my favorite color so..",
            "I'm single bc I hate people but I want to find 1 person who I don't hate who also hates people",
            "Cocaine could be legal, but rich people are the #1 consumers & they refuse to pay taxes",
            "Daddy issues, multiple guy friends, no drivers license…just my type!",
            "If u see me acting different, it's bc I started watching a new show n adopted the personality of the main character",
            "U accused me of spending too much money, but the whole time u had more credit card debt than the national debt",
            "Broke, 2 baby mommas and a jail record? Yes, lets get married",
            "If u think money doesn't bring happiness transfer it my account",
            "Don't tell me not to give up on my dreams, do u want me to get out of bed and go to work or not",
            "I know he cheated in the past but this time its different, I can fix him",
            "My standards are high bc I can provide what I require",
            "Parents should never say 'u remind me of me', how insulting",
            "Yes, she has a past, but she's changed woman, I think I can mold her into wifey material",
            "Me needing constant reassurance that my friends actually like me",
            "Insurance is useless unless it's dating, then a backup plan ain't so bad",
            "He just has a few smalls screws missing, nothing too crazy",
            "My dumb self be loyal before the relationship even starts",
            "If I have an ugly baby it ain't my fault, have u seen my baby mommas uncles",
            "I let my 90 day fiance borrow my social security card",
            "I'm both a 'fast replier' and 'never replies' type of person. it depends on my mood",
            "No ones perfect huh, that's a sign I shouldn't get married, I don't want no flawed person",
            "I hate to see a girl hurt my guy friend so I stay on standby for his revenge s*x",
            "I'm that person who sticks around longer than I should. But once I'm gone, I'm gone",
            "We had it wrong all these years, a baby daddy is a pregnant gay man",
            "I love when he hugs me from behind at the cash register",
            "Me thinking I look friendly and I actually look llike scar from lion king",
            "I don’t like that 'new year, new me' crap..PUH-lease, u'll be back with rayray tmoro mornin",
            "IMMA STCK BESIDE HIMM!!",
            "More attracted to interesting people rather than hot people",
            "How dare u let me get back with my ex 5 times this month",
            "Its not u its ME",
            "I'm sensitive not soft, I'll slap u while I'm crying",
            "I social distance online too, most of yall toxic af",
            "Of course u can borrow my car while I'm at work to pick up ur baby momma and my step kids",
            "U think u can hurt me? I'm an overthinker, I already knew u were gonna hurt me",
            "Plan B must taste nasty af, bc ya'll acting like Nick Cannon out here",
            "Me at a strip club: Let me take u away from all of this",
            "If I keep staring at the wall then they wont know im here",
            "I guess I'm the only one who doesn't go to the club every weekend",
            "u right, I should have taken 'I don’t wan't food' as a clear sign u were hungry",
            "If it lasted less than 5 minutes, it did NOT happen",
            "Alot of yall starting to grow stomaches on ur backs",
            "OMG how could I forget u wanted .0223oz of herseys syrup on ur ice cream",
            "Calling in sick knowing I have a NEGATIVE 40 hour vacation balance",
            "Oh, u're a model on IG? Cool, I'm a soldier on call of duty",
            "My bad, I should have known u were having a nightmare and called to wake u up",
            "They need to make new animals..I'm tired of chicken, beef and fish",
            "Throw that money tree away, u been broke for centuries",
            "If I catch u cheating I understand it was my fault for snooping around in the first place",
            "Cheat on me once, I'll have a baby on u twice",
            "Don’t come around me with ur underarms smelling like onions and blue cheese",
            "My bad, I should have seen that coming. I guess my psychic abilities were off today",
            "I failed science but I do NOT trust those atoms, I heard they make up everything",
            "How u mad before breakfast? Like brush ur teeth first at least",
            "It's my fault, I should have used my time-traveling abilities to prevent that from happening",
            "Tech support keep telling me to close my windows but they been shut..I even turned the heat on",
            "I post sad meme's hoping he'll see it and change…",
            "Me: in school loan debt: Also Me: Sure, u can borrow $500",
            "I wish I could take my fav parts of a woman and combine them all into one",
            "I act like it's cool but deep down I'm judging u",
            "Watching lil Jimmy curse out his mom Me: Give me 1 day, that'll be the last f bomb he drops",
            "Ya'll out here having kids just for the tax credits",
            "Sexy uber driver... Me: I know u tired of driving, come be my passenger princess",
            "Sure I'll pay all the bills..Just know im about to control u so we can make it last",
            "He's a good man, Savannah. A GOOD man.",
            "Ya'll poop like once a week, that’s why yall backs big as it is",
            "Who came up with selfie? It should be self-ish"
        ]


    ]
    
}
